### ISSUE TITLE
poor parallelization for cnvkit (sambamba depth)

### ISSUE THREAD

**Issue by brentp** [chapmanb/bcbio-nextgen#1528] opened 2016-08-23 21:20 UTC
I have this running now:

```
sambamba depth window -t 16 -c 72.272 --window-size 250 -T 1445 /scratch/ucgd/lustre/u6000771/bcbio/eiee/work-subset/prealign/15-0022949/15-0022949.bam | /uufs/chpc.utah.edu/common/home/u6000771/bcbio/anaconda/bin/py -fx 'float(x.split()[5]) >= 25.0 if not x.startswith("#") else None' | cut -f 1-3,7 > /scratch/ucgd/lustre/u6000771/bcbio/eiee/work-subset/align/15-0022949/tx/tmpWq5Dyz/15-0022949-highdepth-raw.bed
```

The output in the log for that is:

```
...
[2016-08-23T20:31Z] Identify high coverage regions
[2016-08-23T20:31Z] Processing reference #1 (1)
[2016-08-23T20:38Z] Processing reference #2 (2)
[2016-08-23T20:45Z] Processing reference #3 (3)
[2016-08-23T20:51Z] Processing reference #4 (4)
[2016-08-23T20:58Z] Processing reference #5 (5)
[2016-08-23T21:07Z] Processing reference #6 (6)
[2016-08-23T21:15Z] Processing reference #7 (7)
```

and it's only using at most 2 CPUs. Would it be possible to parallelize this by sample to get better CPU utilization?

**Comment by chapmanb** [comment] 2016-08-24 01:34
Brent;
This appears to be IO constrained on the machine since sambamba is getting all 16 cores to work with on the command line. So we're trying to make use of cores effectively but it's just not working out resource usage wise.

Currently there is not an easy way to re-parallelize in a different manner since it happens on a cluster in the same block as alignment so gets a machine with allocated cores (16 in this case) to work with during this whole block of processing. The current work on CWL support will make this step more flexible since each individual step can get exactly the required resources for it.

**Comment by brentp** [comment] 2016-08-29 15:31
Brad, we just added an option to etal/cnvkit to parallelize the coverage part (with -p). Maybe this can be added to bcbio at some point?
Once I have another chance I'll add parallelization to the segmentation step as well.

**Comment by chapmanb** [comment] 2016-08-29 21:38
Brent -- awesome, thanks for doing that and looking through all the slow points. This is much appreciated. I'd definitely like to add the parallelization improvement once there is a new CNVkit release. I know there are some structural changes in formats in the current development version so when @etal thinks it's ready we can work on migrating bcbio over and incorporating this.

**Comment by etal** [comment] 2016-08-30 18:13
Thanks for working on this! I filed a couple more issues to address in this at etal/cnvkit#123 and etal/cnvkit#124.

I'm planning to roll a CNVkit v0.8 release fairly soon, after some modest changes to VCF input handling which shouldn't affect bcbio. The file format changes are fairly modest and should be backwards-compatible for the v0.8 series, but there are more significant internal changes that it would be nice to test with bcbio before the official release if that's possible.

**Comment by chapmanb** [comment] 2016-08-30 19:40
Eric;
Should the current development version be working with all of your new changes? I ran into a few issues earlier but thought it might be due to ongoing development. If you expect all to work I can reproduce and debug from the point right now before the next release. Thanks so much for all the work on this.

**Comment by etal** [comment] 2016-08-31 00:08
As of a few minutes ago, yes, CNVkit dev should be CLI-stable and ready for testing. VCF handling in particular could benefit from some road testing with the newer variant callers and GATK 3.

I'll work on updating the documentation. Would it help if I made a pre-release available on GitHub, including release notes?

**Comment by brentp** [comment] 2016-08-31 01:29
if you had issues, it was likely right after etal/cnvkit#121 was merged. I introduced a few problems in there that Eric has (hopefully) resolved.

**Comment by brentp** [comment] 2016-08-31 18:30
Brad, this is (I assume) unrelated to this issue, but with lumpy+cnvkit, I"m seeing:

```
subprocess.CalledProcessError: Command 'set -o pipefail; cat /scratch/ucgd/lustre/u6000771/bcbio/eiee/work-subset/structural/15-0022951/lumpy/15-0022951-svs.vcf | grep -v ^##contig | bcftools annotate -h /scratch/ucgd/lustre/u6000771/bcbio/eiee/work-subset/structural/15-0022951/lumpy/tx/tmpmg9ja5/15-0022951-svs-prep-header.txt | vt sort -m full -o /scratch/ucgd/lustre/u6000771/bcbio/eiee/work-subset/structural/15-0022951/lumpy/tx/tmpmg9ja5/15-0022951-svs-prep.vcf.gz -
[W::vcf_parse] contig 'hs37d5' is not defined in the header. (Quick workaround: index the file with tabix.)
```

I can see that the catted VCF is valid, however, vt seems to require that the ##contig lines are in the header in order to sort it.

**Comment by brentp** [comment] 2016-08-31 18:43
As it goes, after posting I realized the error is because the bams were called with genome that included 'hs37d5'

**Comment by chapmanb** [comment] 2016-09-08 05:45
Eric and Brent -- thanks much, you were both right on, I must have hit an in-progress problem. I tested the latest development on some larger datasets and only found one small issue that I sent a PR for (etal/cnvkit#128)  but otherwise it looks great. I can definitely migrate to the latest development (or a release, if we're ready for that) and incoporate Brent's improvements in bcbio. Thanks again.

**Comment by lpantano** [comment] 2017-03-14 20:21
Hi all,

I am closing this because it seems is not a problem anymore, please feel free to open an issue if you find again the problem.

thanks!

**Closed by lpantano** 2017-03-14 20:21 UTC
