### ISSUE TITLE
Automated sample configuration only works with .fastq.gz files

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#860] opened 2015-05-25 08:40 UTC
I tried making a sample configuration (with template and so on) using ready-made BAM files to prevent yet another alignment run, but when running bcbio_nextgen I was greeted with "metadata not found" for each of the samples.

Example YAML produced by the run:

````yaml
  description: 10152
  metadata:
    batch: OTH14
  files:
  - /mnt/data/projects/OTH-14/bam/10152.bam
````

The file names and the metadata are identical, but they don't get picked up, somehow.

**Comment by chapmanb** [comment] 2015-05-25 10:12
Luca;
Sorry about the issue, I'm not sure exactly what is going wrong here, as this should work. Would you be able to post a minimal example with a single template line and file that doesn't behave as expected? We can try to reproduce and debug from that. Your example also indicates that metadata finding worked, since it has a batch specified, so maybe the metadata not found is for a different sample? Or is it pulling in the batch information from a PED file or other external source? Thanks again for the report and happy to try and make this all work better/clearer.

**Comment by lbeltrame** [comment] 2015-05-25 10:14
> finding worked, since it has a batch specified, so maybe the metadata not
> found is for a different sample? Or is it pulling in the batch information

In part I'm silly, because I posted a file *after* I fixed it manually ;)
I'll try to get a minimal, one-sample template and report back.

**Comment by lpantano** [comment] 2016-04-24 23:12
Hi,

I close this since I think we pushed a fix for that a while ago. If you find any further problem, let us know. Thanks!

**Closed by lpantano** 2016-04-24 23:12 UTC
