### ISSUE TITLE
mark_duplicates command - error relating to a lack of bam indexes being generated for intermediary bam

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1091] opened 2015-11-01 14:02 UTC
Hi 
I am trying to run some amplicon data through your pipeline but setting the mark_duplicates to false seems to throw an error relating to the absence of a bam index file being generated for one of the bam intermediary files ending `reorder-firgs-gatkfilter.bam`. Not sure if I am setting this correctly but if I remove the setting it seems to run fine.
My yaml file looks like:
```
upload:
  dir: final
details:
- algorithm:
    merge_bamprep: true
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: [gatk-haplotype, samtools, platypus]
    validate: ../input/regions.vcf
    ensemble:
      numpass: 2
  analysis: variant2
  description: NGSfiletest
  files: [/home/file1_L001_001_1.fastq.gz, /home/file2_L001_001_2.fastq.gz]
  genome_build: GRCh37
fc_date: '2015-10-09'
fc_name: qxtindel1
```

**Comment by chapmanb** [comment] 2015-11-01 19:29
Sorry about the issues. I'm trying to reproduce this and can't based on your input configuration. A couple of thoughts/questions:

- What version of bcbio are you running? There were some recent fixes in the latest release around correctly creating BAM indices.
- Is the minimal YAML posted representative of the full run? The `gatkfilter.bam` files normally come from pre-aligned inputs being cleaned up with `aligner: false` and `bam_clean: picard`. It might be possible I'm missing something trying to replicate.

Hope this helps some and happy to try and debug more with additional information.

**Comment by kevjp** [comment] 2015-11-02 10:10
I am running v0.9.3 so I upgraded to v0.9.4 `sudo bcbio_nextgen.py upgrade -u stable`. This got me over the indexing issue but generated an input/output error. So i then upgraded the third party tools `bcbio_nextgen.py upgrade -u stable --tools` and this seems to have got over the I/O error. It is running at the moment so will get back to you if I experience any further problems. Thanks for the help.

**Comment by lpantano** [comment] 2016-06-23 16:52
closing this since it seems it worked at the end, great!

thanks so much

**Closed by lpantano** 2016-06-23 16:52 UTC
