### ISSUE TITLE
Installation fails at building expat

### ISSUE THREAD

**Issue by drjrm3** [chapmanb/bcbio-nextgen#825] opened 2015-04-14 13:35 UTC
I am trying to install bcbio-nextgen on a Fedora 21 system (as a template for a cluster installation on RHEL). I get 

[localhost] local: /apps/bcbio-nextgen/install/bin/brew tap
[localhost] local: /apps/bcbio-nextgen/install/bin/brew update
[localhost] local: /apps/bcbio-nextgen/install/bin/brew tap homebrew/science
[localhost] local: /apps/bcbio-nextgen/install/bin/brew tap chapmanb/cbl
[localhost] local: /apps/bcbio-nextgen/install/bin/brew tap --repair
[localhost] local: /apps/bcbio-nextgen/install/bin/brew outdated
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/apps/bcbio-nextgen/install/lib/perl5:${PERL5LIB} && /app
Traceback (most recent call last):
  File "/apps/bcbio-nextgen/vendor/bcbio-nextgen/scripts/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 210, in _install_pkg_latest
    cmd.replace("brew install", "brew install -v"))
ValueError: Failed to install brew formula: expat
To debug, please try re-running the install command with verbose output:
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/apps/bcbio-nextgen/install/lib/perl5:${PERL5LIB} && /apps/bcbio-nextgen/ins
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 259, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main 
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd) 
subprocess.CalledProcessError: Command '['/apps/bcbio-nextgen/install/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/apps/bcbio-nextgen/install', '--i

as an error when running the following commands for installation:

#!/bin/bash
python bcbio_nextgen_install.py /apps/bcbio-nextgen/install --tooldir=/apps/bcbio-nextgen/install --isolate --genomes GRCh37 --aligners bwa --aligners bow

My Python version is 2.7.8 if it matters.

**Comment by chapmanb** [comment] 2015-04-14 13:46
Robert;
Sorry about the problem and thanks for the detailed report. It looks like it is failing when building expat for some reason. Could you try running the debug command suggested in the error output:
```
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/apps/bcbio-nextgen/install/lib/perl5:${PERL5LIB} && /apps/bcbio-nextgen/install/bin/brew install -v --env=inherit expat
```
This should provide a more useful traceback about why it fails. You can post the full log file as a Gist (https://gist.github.com/) and link to it here instead of needing to copy paste in. Hope this helps.

**Comment by drjrm3** [comment] 2015-04-14 14:34
The output is rather short, so I will just paste it here:

==> Downloading https://downloads.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.1.5-273; x86_64-linux) https://downloads.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz -C 0 -o /home/jmichael/.cache/Homebrew/expat-2.1.0.tar.gz.incomplete --insecure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) TCP connection reset by peer
Error: Failed to download resource "expat"
Download failed: https://downloads.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz

**Comment by chapmanb** [comment] 2015-04-14 15:08
Rob;
It looks like something is problematic about accessing sourceforge from your machine. It downloads fine for me here so if it's a persistent error you might have to debug some. Does it download manually using curl:
```
/usr/bin/curl -fLA 'Homebrew 0.9.5 (Ruby 2.1.5-273; x86_64-linux)' https://downloads.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz -C 0 -o expat-2.1.0.tar.gz
```
If you can manage to download it you can put it manually in `~/.cache/Homebrew` and brew will grab it from there. If it's an issue with multiple downloads, you probably don't want to keep doing this and might have look into the connectivity issues. Hope this helps some.

**Comment by drjrm3** [comment] 2015-04-14 15:41
Thanks - I am not able to download it via curl so I have downloaded the tar file and compiled it. In the /apps/expat/install/2.1.0/bin directory, I only have 'xmlwf' and there is no 'expat' executable. Is this the correct outcome? Is this executable what I put in `~/.cache/Homebrew`? 

If so (and even if not) the `~/.cache/Homebrew` folder is in my local directory and I am trying to simulate this installation in a global location for a cluster. Does there need to be a global `.cache/Homebrew` or is this for installation purposes only and the local nature of this directory will not affect the final executables/installation of bcbio-nextgen?

**Comment by chapmanb** [comment] 2015-04-14 16:24
Rob;
Apologies for the confusion, you only need to move the tarball, named `expat-2.1.0.tar.gz` into `~/.cache/Homebrew` and then re-run the bcbio installation. It will handle the rest of the installation of expat, and will put it into the final bcbio-nextgen directory.

More generally, bcbio is going to download a lot of files for installation via curl so it would be worth diagnosing and fixing the underlying issue so you don't have to do this manually for every tool. Hope this helps.

**Comment by drjrm3** [comment] 2015-04-15 18:50
After pulling the expat version manually by using `http` rather than `https` the installation now fails at

[localhost] local: /apps/bcbio-nextgen/install/bin/cpanm -i --notest --local-lib=/apps/bcbio-nextgen/install ==> Found dependencies: ExtUtils::MakeMaker, ExtU
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.04.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.04 ... Can't locate ExtUtils/Manifest.pm in @INC (you may need to install the ExtUtils::Manifest module) (@INC contains: FatP
OK

Fatal error: local() encountered an error (return code 1) while executing '/apps/bcbio-nextgen/install/bin/cpanm -i --notest --local-lib=/apps/bcbio-nextgen/i

Aborting.
'Encode::Locale'
local() encountered an error (return code 1) while executing '/apps/bcbio-nextgen/install/bin/cpanm -i --notest --local-lib=/apps/bcbio-nextgen/install 'Encod
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 259, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main 
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd) 
subprocess.CalledProcessError: Command '['/apps/bcbio-nextgen/install/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/apps/bcbio-nextgen/install', '--i

Should I open a new report for this?

**Comment by chapmanb** [comment] 2015-04-16 00:29
Rob;
Sorry about the issue. I believe recent versions of the RedHat/Centos/Fedora only install a very minimal Perl which doesn't have enough dependencies to build packages. I updated the docs with the dependencies for Perl you'd need (`perl perl-devel perl-core`):

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

If you install these you should hopefully have a workable Perl for installing these dependencies. I'm still worried about being unable to download https packages and think the system might need some SSL updates, but hope this at least gets you further in the process.

**Comment by drjrm3** [comment] 2015-04-16 00:35
OK. I will install these perl libraries on my desktop and continue with the
installation. For further issues in the installation should I make a new
thread or just keep posting in this?

**Comment by chapmanb** [comment] 2015-04-16 00:50
This thread is fine with me, I'll leave it open. Thanks for all the patience getting it running.

**Comment by drjrm3** [comment] 2015-04-16 16:27
Thanks. I am continuing to get a lot of errors on installation due to curl.
We have some firewalls in place that are not playing nice with
https://*whatever*.sourceforge.*whatever*
so I am having to install, then wait for it to crash, then wget the file by
hand via http://*whatever.sourceforge.*whatever* and put it in
.cache/Homebrew

Where might I find a list of files which will need to be retrieved in this
manner so that I can install them all once and then put them in the correct
location? I may end up trying to just keep this folder and loading this
onto the cluster once I get to that phase so that I don't have to worry
about wget or curl since the cluster is actually behind a second firewall.

**Comment by jgbaum** [comment] 2015-04-16 20:15
Just a note that I'm running into the exact same issues as drjrm3 on a ROCKS 6.1 cluster running Redhat 6.3.  Any info regarding the filed needed from sourceforge would greatly help me out as well. Thank you!

**Comment by jgbaum** [comment] 2015-04-16 20:45
Actually, my issue seems to be slightly different, but possibly related to expat as well.  Here is the command I am using to install:

```python bcbio_nextgen_install.py /share/apps/bcbio/data/ --tooldir=/share/apps/bcbio/tools --genomes GRCh37 --genomes mm9 --genomes mm10 --distribution centos --aligners bwa --aligners bowtie2```

And here is the last successful message, followed by the error message:

https://gist.github.com/jgbaum/cada446ca115b8a81f5f#file-bcbio_install_error

For troubleshooting, it asks me to run the following command:

```export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/share/apps/bcbio/tools/lib/perl5:${PERL5LIB} && /share/apps/bcbio/tools/bin/brew install -v --env=inherit   expat```

Here is the output:

https://gist.github.com/jgbaum/73d98a6eea2b1a3d824b#file-bcbio_troubleshooting

I have tried manually downloading expat with curl from the same node and it worked. I then placed the expat tarball into the ~/.cache/Homebrew directory (which I had to create), and reran the initial command, but received the same error message.  Any help would be much appreciated.

**Comment by chapmanb** [comment] 2015-04-16 21:36
Rob;
I don't have any list of downloads but it is going to be a lot of things. It would be pretty painful to do this on a system without a working internet connection. Is it possible to sort out why you can't connect to sourceforge upstream?

@jgbaum -- It looks like you need to install the `ruby-irb` package and then it should start working cleanly. More details on required installation packages are here (https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations). Hope this gets it running for you.

**Comment by lpantano** [comment] 2015-04-16 23:03
Hi @jgbaum, I am with Brad that will be painful, and for updates as well. I will go for finding the problem.
 To have the list of files, I would install bcbio in a computer outside the firewall, and get all download files from ~/.cache/homebrew you have after installation and move that to the cluster or computer you are having the problem. Not sure if that would work but is the only way I can think of get all files.

**Comment by jgbaum** [comment] 2015-04-17 23:06
Thanks, @chapmanb! That got me most of the way.  I'm running into one more error which seems to be caused by an mm9 annotation file missing:

https://gist.github.com/jgbaum/c5bfea5e1b13afb6b867#file-file_not_found_error

Would you mind helping to shed light on this one?  Thanks and have a great weekend!

**Comment by chapmanb** [comment] 2015-04-18 10:04
Sorry about the issue, we needed to refresh the snpEff databases for the latest release. I pushed new resource files so if you re-run it should pick up where it left off and hopefully finish cleanly. Glad it's mostly working for you now and thanks for trying bcbio out.

**Comment by jgbaum** [comment] 2015-04-18 17:48
Install ran to completion.  Thank you!

**Comment by drjrm3** [comment] 2015-04-28 14:42
I now have it installed on the local desktop and am trying to install it on
the cluster and have different errors. I am getting the following now:

export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export
PERL5LIB=/hpcf/apps/bcbio-nextgen/install/0.8.7/lib/perl5:${PERL5LIB} &&
/hpcf/apps/bcbio-nextgen/install/0.8.7/bin/brew install -v --env=inherit
expat
==> Downloading
https://downloads.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz
Already downloaded: /home/jmichael/.cache/Homebrew/expat-2.1.0.tar.gz
==> Verifying expat-2.1.0.tar.gz checksum
Error: libcrypto.so.6: cannot open shared object file: No such file or
directory -
/nfs_exports/apps/64-bit/gnu-apps/ruby/ruby-1.9.2-p180/lib/ruby/1.9.1/x86_64-linux/digest/sha1.so
Please report this bug:

https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
<internal:lib/rubygems/custom_require>:29:in `require'
<internal:lib/rubygems/custom_require>:29:in `require'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/extend/pathname.rb:259:in
`sha1'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/extend/pathname.rb:270:in
`verify_checksum'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/resource.rb:120:in
`verify_download_integrity'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/resource.rb:80:in
`stage'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/formula.rb:879:in
`stage'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/formula.rb:511:in
`brew'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/build.rb:107:in
`install'
/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Library/Homebrew/build.rb:179:in
`<main>'
[jmichael(BASH)@nodecn001]: /hpcf/apps/bcbio-nextgen/install/0.8.7/bin/brew
update

it seems like maybe ruby is installed in a location on the shared file
system that bcbio-nextgen can't get to maybe? If this is the problem I will
install a newer version of ruby and load that version before installation,
but I want to make sure that is the problem before I go through that
trouble.

**Comment by chapmanb** [comment] 2015-04-28 18:01
Robert;
I agree with your assessment, there is something problematic with Ruby on the system. I don't think this is anything bcbio specific but gets exposed when calling brew to do crypto related work. In this case it is when it tries to calculate the sha1 checksum.

Your ruby installation expects libcrypto.so.6. You might have updated ssl at some point without updating the ruby package. It's hard to debug this remotely but this thread with cheap symlink workarounds might help:

http://forums.fedoraforum.org/showthread.php?t=115575

Hope this gets things going for you.

**Comment by drjrm3** [comment] 2015-04-29 16:01
I installed a new version of ruby and I got past that problem, but now I'm
getting another weird error. The error file is posted at
https://gist.github.com/drjrm3/b98506f40561e46df2d6 and the offending
command is:

export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export
PERL5LIB=/hpcf/apps/bcbio-nextgen/install/0.8.7/lib/perl5:${PERL5LIB} &&
/hpcf/apps/bcbio-nextgen/install/0.8.7/bin/brew install -v --env=inherit
vep

**Comment by chapmanb** [comment] 2015-04-30 09:57
Robert;
Glad that fixed the Ruby issue. The error here looks like it's having trouble downloading VEP dependencies from CPAN, specifically BioPerl:
```
 - fetching BioPerl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) couldn't connect to host
 - unpacking /sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Cellar/vep/75_2014-06-12/lib/Bio/tmp/BioPerl-1.6.1.tar.gz
Unable to extract '/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Cellar/vep/75_2014-06-12/lib/Bio/tmp/BioPerl-1.6.1.tar.gz':  at /sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Cellar/vep/75_2014-06-12/INSTALL.pl line 851
Error listing contents of archive '/sonas/hpcf/apps/bcbio-nextgen/install/0.8.7/Cellar/vep/75_2014-06-12/lib/Bio/tmp/BioPerl-1.6.1.tar.gz': /bin/tar: This does not look like a tar archive
/bin/tar: Exiting with failure status due to previous errors
```
It might be worth re-running to see if this is a temporary network issue and if not trying to see if there is some kind of network/proxy issue blocking BioPerl. Sorry to not have a more precise idea of what is happening but hope this helps.

**Comment by drjrm3** [comment] 2015-04-30 12:29
Thanks. I saw that the error looks like it is stemming from curl on
Bioperl, but there isn't a whole lot of information there telling my why it
can't connect. In the past it seems like I got more detailed information on
why it couldn't complete the download. Any ideas on how to debug the issue?
I have tried the download a few more times since then and consistently get
this issue.

For example, where is it fetching BioPerl from? Perhaps there is another
firewall/port issue that I need to look into.

**Comment by chapmanb** [comment] 2015-05-01 20:27
Robert;
Sorry about my non-precise answer. This code is inside the Variant Effects Predictor installer so I had to dig to see where it download from. The current version we're using gets it from http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz:

https://github.com/Ensembl/ensembl-tools/blob/3bf1764e3ffdc7cba9821101a0592527ebd7b751/scripts/variant_effect_predictor/INSTALL.pl#L61

We're planning to soon move to the most recent VEP to support both GRCh38 and 37, which uses a GitHub location and may work better:

https://github.com/Ensembl/ensembl-tools/blob/4a86cbf5b2229cef36dda20492f7678cdbd0f466/scripts/variant_effect_predictor/INSTALL.pl#L62

That will take a bit of work to update and debug but if you can't figure out the download issue I can report back here when we're using the latest VEP version. Sorry again about the problems and hope this helps.

**Comment by lpantano** [comment] 2016-04-24 23:19
Hi!

I will close this since we moved to bioconda now and supporting both of those genome! thanks a lot for you help debugging!

**Closed by lpantano** 2016-04-24 23:19 UTC

**Comment by rbagnall** [comment] 2016-04-29 00:48
I arrived here due to issues with installing VEP. This post closed 4 days ago, but anyway, to resolve the issue the Variant Effects Predictor installer script should get BioPerl from

http://www.bioperl.org/DIST/BioPerl-1.6.1.tar.gz

not

http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz
