### ISSUE TITLE
Wrong/missing dependencies in some packages

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2055] opened 2017-08-31 09:40 UTC
After updating after 3 weeks, some of the bits installed aren't properly working in the R bits:

- R will not start (missing pcre; solved by installing it)
- R has issues loading Tcl
- RCurl is missing icu=58.1, but that soversion is in conflict with other packages (r-fnn, which is needed by bubbletree)

I'm triple-checking if there are issues I brought upon myself, though.

**Comment by chapmanb** [comment] 2017-09-01 01:18
Luca;
Sorry about all these issues, I'm not able to replicate them when updating on some of my systems so am not sure what happened. Is it possible you had an older cached cloudbiolinux in `tmpbcbio_install` that ran instead of the latest? We have some work in there which tries to cleanly upgrade R between versions. You should end up with 3.3.2 after running the upgrade. Thanks for the help debugging.

**Comment by lbeltrame** [comment] 2017-09-01 09:17
I removed folders but that didn't solve the problem. It looks like icu isn't updated for some reason, I'll investigate.

**Comment by lbeltrame** [comment] 2017-09-04 08:14
On a fresh reinstall of the software (I wiped things clean just to make sure), I get the output below (after the "quiet" install of other packages). Once the installation finishes I'll check if everything is working as intended.

```
The following packages will be UPDATED:

    reportlab:                           3.4.0-py27_0                  conda-forge --> 3.4.0-py27_0                             
    scipy:                               0.19.1-np113py27_nomkl_0                  [nomkl        ] --> 0.19.1-py27_blas_openblas_202 conda-forge [blas_openblas]
    statsmodels:                         0.8.0-np113py27_0             conda-forge --> 0.8.0-np112py27_0             conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    numpy:                               1.13.1-py27_nomkl_0                       [nomkl        ] --> 1.12.1-py27_blas_openblas_200 conda-forge [blas_openblas]
    readline:                            6.2-2                                     --> 6.2-0                         conda-forge

The following packages will be DOWNGRADED:

    fontconfig:                          2.12.1-4                      conda-forge --> 2.11.1-6                      conda-forge
    freetype:                            2.7-1                         conda-forge --> 2.6.3-1                       conda-forge
    icu:                                 58.1-1                        conda-forge --> 56.1-4                        conda-forge
    libxml2:                             2.9.4-4                       conda-forge --> 2.9.4-3                       conda-forge
    matplotlib:                          2.0.2-py27_2                  conda-forge --> 2.0.0-np112py27_1             conda-forge
    pillow:                              4.2.1-py27_1                  conda-forge --> 4.0.0-py27_1                  conda-forge
    pyqt:                                5.6.0-py27_4                  conda-forge --> 4.11.4-py27_2                 conda-forge
    qt:                                  5.6.2-3                       conda-forge --> 4.8.7-3                       conda-forge
```

**Comment by lbeltrame** [comment] 2017-09-04 11:49
The install was obviously very old (2+ years). After cleaning it up, it *seems* to work correctly. I'll reopen if anything else comes up.

**Comment by lbeltrame** [comment] 2017-09-04 12:37
Spoke too soon:

```
> library(RCurl)
Loading required package: bitops
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/storage/rozo/bcbio/anaconda/lib/R/library/RCurl/libs/RCurl.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
Error: package or namespace load failed for 'RCurl'
```

**Comment by lbeltrame** [comment] 2017-09-04 12:41
Other bits (perhaps less interesting, but noteworthy):

```
> library(tcltk)
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Can't find a usable init.tcl in the following directories: 
    /opt/anaconda1anaconda2anaconda3/lib/tcl8.5 ./lib/tcl8.5 ./lib/tcl8.5 ./library ./library ./tcl8.5.18/library ./tcl8.5.18/library



This probably means that Tcl wasn't installed properly.

Errore: package or namespace load failed for ‘tcltk’
```

**Comment by lbeltrame** [comment] 2017-09-04 14:11
I had to do

```
conda install -c conda-forge -c bioconda icu==58.1
```

To get things back on track.

**Comment by lbeltrame** [comment] 2017-09-04 15:32
An update downgrades things, therefore breaking everything again. I fear there might be something built against icu 58 and something against icu 56.

**Comment by chapmanb** [comment] 2017-09-04 19:14
Luca;
Sorry about the issues. I can confirm that icu creates a lot of issues and often switched back and forth between 36 and 38 because different tools pin it to different versions.

Which tools in bcbio does this break that require Rcurl? Can you provide a traceback of where pipelines are failing? I think our best bet here is to try and create an isolated environment with R but I've been trying to delay that until all of the bioconda R modules update to 3.4. Perhaps there is a way to work around this in the short term and avoid breaking your runs. Thanks much for the help debugging.

**Comment by lbeltrame** [comment] 2017-09-06 12:36
Currently it's running, I'll report back if there are clear issues. However, this bit me because I was testing TitanCNA, whose installation depends on both RCurl and XML. So it's likely that we'll run into this sooner or later.
Probably an isolated R prefix would work best.

**Comment by chapmanb** [comment] 2017-09-07 10:36
Luca -- thanks much for investigating. I'm hoping to add TitanCNA and pureCN packages soon so will investigate once those are in place and R 3.4 is available. We'll definitely isolate R if we can't resolve the icu issues. I'll close this for now and we can re-open if we hit problems. Thanks again.

**Closed by chapmanb** 2017-09-07 10:36 UTC
