### ISSUE TITLE
Install old version of bcbio

### ISSUE THREAD

**Issue by tcezard** [chapmanb/bcbio-nextgen#1407] opened 2016-05-27 15:53 UTC
We are migrating hardware but we need to continue to run the same version of bcbio to be consistent across samples.
When I install bcbio from the tagged version of the install script (eg: [0.9.4](https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/v0.9.4/scripts/bcbio_nextgen_install.py)), then it still installs the latest version from master.
How can I install a specific version of bcbio?

Thank you

**Comment by chapmanb** [comment] 2016-05-27 17:42
Timothee;
We don't have a mechanism to install old versions of bcbio with all the tools and data dependencies. This is a difficult problem as it requires having fully reproducible installs of all the prior tools. We've been moving towards supporting this in two ways: running bcbio inside Docker containers and migrating tool installation to conda where we can readily get and install old versions.

Sorry to not have a good setup to make this easily possible now. Hopefully tracking the latest work or reprocessing older batches with new related samples is an option without disrupting your analyses.

**Comment by lpantano** [comment] 2016-12-16 23:01
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers

**Closed by lpantano** 2016-12-16 23:01 UTC

**Comment by pfujita** [comment] 2017-03-08 20:04
Hi @chapmanb and @lpantano,

We also need to be able to reproducibly install an old version of bcbio. In particular, we want to copy our existing installation (which is behind the current version of  your repo) to a second location. Can we: 1. Simply copy the tree over, or are there hidden config files/pointers that will be specific to the installation's location? or 2. If we can't copy it, could we clone the older tagged version of the bcbio repo to a new location and hook it up to all the same versions of data and tools as our first installation? If 2 is the way to go, is there an automated way to point it at a set of tool and data paths, or will we need to do each tool and dataset manually (and if the latter - do we change this from the system.yaml?).

Thanks in advance for your help!
Pauline

**Comment by chapmanb** [comment] 2017-03-08 20:34
Pauline;
Unfotunately we don't have a way to do this cleanly right now. As I mention above we're actively working on doing this using Docker contains but that's still a work in progress.

If you copy an existing bcbio installation it's going to have hard coded paths to the previous installation, both within bcbio configuration files and the conda installation. bcbio is possible but adjust and would require manually changing the paths in the configuration files to point at the new directory structure. conda uses absolute paths for executables and binaries so would be harder to manually fix. If you'd like to do this by hand you could export your current environment:
```
bcbio_conda list --export > original-tools.txt
```
Then import into your new environment:
```
bcbio_conda install --file original-tools.txt
```
That should hopefully get you most of the way there.

Sorry to not have an automated way to do this right now. This is something we'd like to support and are actively working on it, but synchronizing all of the tools, code and data is a lot of process to put in place. Hopefully this will work for you.

**Comment by schelhorn** [comment] 2017-03-08 20:52
We do this by copying the whole tree (conda and bcbio) to a tar archive, with permissions intact. It's a 250 GB dump that is named according to the bcbio version with an additional time stamp and synced to S3. We have some scripts doing this automatically, so users can go back to previous installs more or less on button press. We haven't tested major release updates of the OS (Ubuntu LTS) yet, though.

**Comment by pfujita** [comment] 2017-03-08 21:38
Thank you @chapmanb and @schelhorn!! These comments are extremely helpful.

**Comment by JJK93** [comment] 2019-05-29 09:12
> We do this by copying the whole tree (conda and bcbio) to a tar archive, with permissions intact. It's based on a userspace-install and results into a 250 GB dump that is named according to the bcbio version with an additional time stamp and synced to S3. We have some scripts doing this automatically, so users can go back to previous installs more or less on button press. We haven't tested major release updates of the OS (Ubuntu LTS) yet, though.

Hi @schelhorn , May I know how we can go back to previous installs using the way you mentioned? Thanks in advance!
