### ISSUE TITLE
SV calling from bam file with sambamba-view:  (Broken pipe)

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1664] opened 2016-11-30 12:56 UTC
Hi,
I run svcaller: [lumpy, manta, cnvkit] from a wgs bam file 

```
 - algorithm:
     aligner: false
     bam_clean: picard
     realign: false
     svcaller:
     - lumpy
     - manta
     - cnvkit
     effects: false
   analysis: variant2
   genome_build: GRCh37
   description: Sample_WGC054948D 
   files:
     - ../../bamfiles/Sample_WGC054948D-ready.bam
```
and the process end up with 
[2016-11-30T03:13Z] sambamba-view:  (Broken pipe)
[2016-11-30T03:13Z] Uncaught exception occurred
```
[2016-11-30T03:12Z] Prepare CNVkit as input for lumpy : Sample_WGC054948D
[2016-11-30T03:12Z] Sort BED file : Sample_WGC054948D
[2016-11-30T03:12Z] Remove high depth regions
[2016-11-30T03:12Z] lumpyexpress : Sample_WGC054948D
[2016-11-30T03:12Z] Sourcing executables from /peterhouse/tools/bcbio/anaconda/bin/lumpyexpress.config ...
[2016-11-30T03:12Z] 
[2016-11-30T03:12Z] Checking for required python modules (/peterhouse/tools/bcbio/anaconda/bin/python)...
[2016-11-30T03:12Z] 
[2016-11-30T03:12Z]     create temporary directory
[2016-11-30T03:12Z] Calculating insert distributions...
[2016-11-30T03:12Z] sambamba-view:  (Broken pipe)
[2016-11-30T03:12Z] Library read groups: Sample_WGC054948D
[2016-11-30T03:12Z] Library read length: 150
[2016-11-30T03:13Z] sambamba-view: unable to write to stream
[2016-11-30T03:13Z] Removed 43 outliers with isize >= 1019
[2016-11-30T03:13Z] done
[2016-11-30T03:13Z] duplicating @PG line SAMBLASTER
[2016-11-30T03:13Z] sambamba-view:  (Broken pipe)
[2016-11-30T03:13Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/peterhouse/tools/bcbio/anaconda/bin:$PATH && lumpyexpress -v -B /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dedup.bam -S /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-sr.bam -D /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-disc.bam -x /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs-exclude.bed -d Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dels.bedpe,Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dups.bedpe -T /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/tx/tmpKVN1im -o /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/tx/tmphk68FS/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs.vcf
Sourcing executables from /peterhouse/tools/bcbio/anaconda/bin/lumpyexpress.config ...

Checking for required python modules (/peterhouse/tools/bcbio/anaconda/bin/python)...

    create temporary directory
Calculating insert distributions... 
sambamba-view:  (Broken pipe)
Library read groups: Sample_WGC054948D
Library read length: 150
sambamba-view: unable to write to stream
Removed 43 outliers with isize >= 1019
done
duplicating @PG line SAMBLASTER
sambamba-view:  (Broken pipe)
' returned non-zero exit status 1
```

is there something i am missing?

**Comment by chapmanb** [comment] 2016-11-30 17:37
Thanks for the report and sorry about the problem. What versions of bcbio and lumpyexpress are you running?
```
bcbio_nextgen.py --version
bcbio_conda list | grep lumpy-sv
```
Ideally you'll have this version of lumpy:
```
lumpy-sv                  0.2.12                   py27_3    bioconda
```
as we pushed a fix for a similar issue in September:

https://github.com/chapmanb/bcbio-nextgen/issues/1055#issuecomment-246758205

If updating doesn't resolve it, could you try running the failing command outside of bcbio to see if you get more helpful error messages:
```
export PATH=/peterhouse/tools/bcbio/anaconda/bin:$PATH && lumpyexpress -v -B /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dedup.bam -S /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-sr.bam -D /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-disc.bam -x /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs-exclude.bed -d Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dels.bedpe,Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dups.bedpe -T `pwd` -o Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs.vcf
```
Hope this helps with debugging and happy to help more.

**Comment by csardas** [comment] 2016-11-30 20:30
hi,

bcbio version is 1.0.0.a0
```
$ bcbio_nextgen.py --version
1.0.0a0
```
and lumpy-sv is 0.2.12
```
$ bcbio_conda list | grep lumpy-sv
Using Anaconda API: https://api.anaconda.org
lumpy-sv                  0.2.12                   py27_3    bioconda
```

and result of test command is
```
Sourcing executables from /peterhouse/tools/bcbio/anaconda/bin/lumpyexpress.config ...

Checking for required python modules (/peterhouse/tools/bcbio/anaconda/bin/python)...

    create temporary directory
Calculating insert distributions...
Library read groups: Sample_WGC054948D
Library read length: 150
Removed 43 outliers with isize >= 1019
done
duplicating @PG line SAMBLASTER

```

thanks very much for fast response and help

**Comment by csardas** [comment] 2016-11-30 20:46
well,
after running the command, I run bcbio_nextgen.py --version again
and something happened 
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/peterhouse/tools/bcbio/anaconda/bin/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, utils, workflow
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 27, in <module>
    from bcbio.variation import effects
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 21, in <module>
    from bcbio.variation import vcfutils
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 19, in <module>
    from bcbio.pipeline import config_utils, shared, tools
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 9, in <module>
    import pybedtools
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 4, in <module>
    from . import long_range_interaction
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/contrib/long_range_interaction.py", line 8, in <module>
    import pandas
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 18, in <module>
    from pandas.core.frame import DataFrame
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 39, in <module>
    from pandas.core.series import Series
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/series.py", line 2944, in <module>
    import pandas.tools.plotting as _gfx  # noqa
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/tools/plotting.py", line 27, in <module>
    import pandas.tseries.converter as conv
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 965, in rc_params
    fname = matplotlib_fname()
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 780, in matplotlib_fname
    cwd = os.getcwdu()
OSError: [Errno 2] No such file or directory

```
I reopen another screen, everything is ok

seems the current path or directory had been changed temporary 
(by sourcing bcbio/anaconda/bin/lumpyexpress.config ?)
and make whole thing strange

**Comment by chapmanb** [comment] 2016-11-30 21:32
Thanks for reporting back. I'm not sure what is going on with the directory changes in your second message but don't think that is related to the underlying issue. In your first followup it looks like lumpyexpress finished successfully outside of bcbio, is that right? I don't see the diagnostic error (` sambamba-view: unable to write to stream`) in that output.

If so, it might indicate a temporary issue like disk space or something else. Does re-running bcbio consistently fail at the same point? If so, can you reproduce with bcbio on a single core (`bcbio_nextgen.py your_config.yaml -n 1`)? That might help us figure out what about the run inside bcbio causes issues. Hope this helps with debugging.

**Comment by csardas** [comment] 2016-11-30 22:06
the command use current directory as a temporary directory, and after the command finished, it delete temporary directory (and it is "current directory" now) automatically! 

any behavior after this command will make shell confused because of "current directory" been deleted.....

**Comment by chapmanb** [comment] 2016-12-01 00:34
Sorry about that issue. I had adjusted the original command line to use the current directory as a temporary directory because it typically uses a temporary directory bcbio creates (which wouldn't exist if you run outside bcbio). Ugh, apologies. I should have adjusted that to a different temporary directory.

That shouldn't effect actual bcbio runs, which do the right thing, so the debugging suggestions above still apply and hopefully will help you move forward. I hope my mistake in manually translating the commandline didn't delete anything of importance.

**Comment by csardas** [comment] 2016-12-02 07:44
oops, I was so lucky for running the command in an empty temporary directory

and running in single thread still get same error

```
[2016-12-01T23:16Z] lumpyexpress : Sample_WGC054948D
[2016-12-01T23:16Z] Sourcing executables from /peterhouse/tools/bcbio/anaconda/bin/lumpyexpress.config ...
[2016-12-01T23:16Z] 
[2016-12-01T23:16Z] Checking for required python modules (/peterhouse/tools/bcbio/anaconda/bin/python)...
[2016-12-01T23:16Z] 
[2016-12-01T23:16Z]     create temporary directory
[2016-12-01T23:16Z] Calculating insert distributions...
[2016-12-01T23:16Z] sambamba-view:  (Broken pipe)
[2016-12-01T23:16Z] Library read groups: 1
[2016-12-01T23:16Z] Library read length: 150
[2016-12-01T23:17Z] sambamba-view: unable to write to stream
[2016-12-01T23:17Z] Removed 43 outliers with isize >= 1019
[2016-12-01T23:17Z] done
[2016-12-01T23:17Z] duplicating @PG line SAMBLASTER
[2016-12-01T23:17Z] sambamba-view:  (Broken pipe)
[2016-12-01T23:17Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/peterhouse/tools/bcbio/anaconda/bin:$PATH && lumpyexpress -v -B /peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/prealign/Sample_WGC054948D/Sample_WGC054948D-ready-dedup-dedup.bam -S /peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/prealign/Sample_WGC054948D/Sample_WGC054948D-ready-dedup-sr.bam -D /peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/prealign/Sample_WGC054948D/Sample_WGC054948D-ready-dedup-disc.bam -x /peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-dedup-svs-exclude.bed -d Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-dedup-dels.bedpe,Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-dedup-dups.bedpe -T /peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/tx/tmpUSCHpR -o /peterhouse/data/DrHsieh_wgs01_12NTpair/ana08_nobamclean/work/structural/Sample_WGC054948D/lumpy/tx/tmpP6Zlja/Sample_WGC054948D-ready-dedup-svs.vcf
Sourcing executables from /peterhouse/tools/bcbio/anaconda/bin/lumpyexpress.config ...

Checking for required python modules (/peterhouse/tools/bcbio/anaconda/bin/python)...

    create temporary directory
Calculating insert distributions... 
sambamba-view:  (Broken pipe)
Library read groups: 1
Library read length: 150
sambamba-view: unable to write to stream
Removed 43 outliers with isize >= 1019
done
duplicating @PG line SAMBLASTER
sambamba-view:  (Broken pipe)
' returned non-zero exit status 1

```

**Comment by chapmanb** [comment] 2016-12-05 11:31
Sorry about the continued issues, I'm not sure what to suggest as we're not getting a good error message to help debug from. I think maybe the temporary directory mistake from above didn't let us finish the test outside of bcbio. Could we try running these two commands:
```
export PATH=/peterhouse/tools/bcbio/anaconda/bin:$PATH && lumpyexpress -v -B /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dedup.bam -S /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-sr.bam -D /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-disc.bam -x /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs-exclude.bed -d Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dels.bedpe,Sample_WGC054948D:/peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dups.bedpe -T lumpy-tmpdir -o Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs.vcf
echo $?
```
To see if it works correctly outside of bcbio? That moves the temporary file creation to another directory so it won't delete anything important during the run. Hopefully it will give us some idea of why lumpyexpress fails so we can debug further. Thanks for the patience trying to work through the issues.

**Comment by csardas** [comment] 2016-12-05 13:19
it return me:

> Error: file /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/bamclean/Sample_WGC054948D/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dedup.bam not found.

**Comment by chapmanb** [comment] 2016-12-06 02:28
Sorry, you'll probably have to do some work with the command line to get it to match your current environment. Basically I want to run the failing command outside of bcbio and am trying to provide guidance but it's a bit tricky to do remotely. It looks like you have changed something as it no longer has split and paired reads in that directory from samblaster, which you need for running lumpyexpress. Did you remove those or otherwise change things in the initial run so these are no longer produced? Hope this helps some with debugging further.

**Comment by csardas** [comment] 2016-12-28 02:43
hi,
I find some time to check this issue again, and rerun the pipeline without any manual operation
the script still returned to me:

> Error: depth bed does not exist: /peterhouse/data/DrHsieh_wgs01_12NTpair/ana06_bam2cnvkit1/work/structural/Sample_WGC054948D/lumpy/Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-dels.bedpe

there is only one file under dir work/structural/Sample_WGC054948D/lumpy/ :

Sample_WGC054948D-ready-reorder-fixrgs-gatkfilter-dedup-svs-exclude.bed

the version of bcbio_nextgen is now 1.0.1a0
the version of lympy is  lumpy-sv      0.2.12       py27_3    bioconda

**Comment by chapmanb** [comment] 2017-01-02 20:16
Thanks for continuing to debug and sorry about the continued issues. If you're also using CNVkit along with lumpy, bcbio will try to use the CNVkit calls as input to Lumpy to improve sensitivity. It looks like there might be no calls for your CNVkit run, leading to missing files. Apologies, I hadn't seen this case before but pushed a speculative fix to try and avoid it. If you update to the latest development version and re-run, does this resolve the issue? Hope this gets things working cleanly for you.

**Closed** 2017-01-19 11:28 UTC

**Comment by chapmanb** [comment] 2017-01-19 11:39
Thanks again for all this debugging. The latest development version now has a cleaned up approach to preparing Lumpy inputs from pre-aligned BAM files that I hope will avoid the issues you saw here (https://github.com/chapmanb/bcbio-nextgen/issues/1738#issuecomment-273754039). Please feel free to re-open if you're still stuck on any issues.

**Comment by csardas** [comment] 2017-01-23 02:32
Thanks for the debugging work and improvement. Thank you.
