### ISSUE TITLE
Ensemble error

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1095] opened 2015-11-03 18:49 UTC
For the mouse whole-genome seq analysis, I deleted the "effects: vep" in the yaml file and re-ran it. The following ensemble error appeared.

[2015-11-03T18:10Z] *.edu: Timing: ensemble calling
[2015-11-03T18:10Z] *: ipython: combine_calls
[2015-11-03T18:10Z] *.edu: Ensemble consensus calls for WT164: freebayes,gatk-haplotype,samtools
[2015-11-03T18:17Z] *.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command './bcbio/bin/bcbio-variation-recall ensemble --cores=16 --numpass 2 ./project/work/ensemble/WT164/WT164-ensemble.vcf.gz ./bcbio/genomes/Mmusculus/mm10/seq/mm10.fa ./project/work/freebayes/WT164-effects-ploidyfix-filter.vcf.gz ./project/work/gatk-haplotype/WT164-effects-ploidyfix-combined-gatkclean.vcf.gz ./project/work/samtools/WT164-effects-ploidyfix-filter.vcf.gz
2015-Nov-03 12:17:04 -0600 *.edu ERROR [bcbio.variation.recall.main] - 
[1;31mjava.lang.ArrayIndexOutOfBoundsException[m: [3m-1[m
                           [37mhtsjdk.tribble.readers.TabixReader.query[m  [32m                 TabixReader.java:  419[m
                            [37mhtsjdk.tribble.TabixFeatureReader.query[m  [32m          TabixFeatureReader.java:  124[m
                        [37msun.reflect.GeneratedMethodAccessor3.invoke[m  [32m                                 :     [m
                    [37msun.reflect.DelegatingMethodAccessorImpl.invoke[m  [32mDelegatingMethodAccessorImpl.java:   43[m
                                    [37mjava.lang.reflect.Method.invoke[m  [32m                      Method.java:  606[m
                        [37mclojure.lang.Reflector.invokeMatchingMethod[m  [32m                   Reflector.java:   93[m
                        [37mclojure.lang.Reflector.invokeInstanceMethod[m  [32m                   Reflector.java:   28[m
[33mbcbio.variation.variantcontext/variants-in-region/[1;33mget-vcs-in-source[m  [32m               variantcontext.clj:  110[m
                                                [33mclojure.core/map/[1;33mfn[m  [32m                         core.clj: 2624[m
                                          [37mclojure.lang.LazySeq.sval[m  [32m                     LazySeq.java:   40[m
                                           [37mclojure.lang.LazySeq.seq[m  [32m                     LazySeq.java:   49[m
                                                [37mclojure.lang.RT.seq[m  [32m                          RT.java:  507[m
                                                   [33mclojure.core/[1;33mseq[m  [32m                         core.clj:  137[m
                                                 [33mclojure.core/[1;33mapply[m  [32m                         core.clj:  630[m
                                                [33mclojure.core/[1;33mmapcat[m  [32m                         core.clj: 2660[m
                                         [37mclojure.lang.RestFn.invoke[m  [32m                      RestFn.java:  423[m
                  [33mbcbio.variation.variantcontext/[1;33mvariants-in-region[m  [32m               variantcontext.clj:  112[m
                  [33mbcbio.variation.variantcontext/[1;33mvariants-in-region[m  [32m               variantcontext.clj:  107[m
                   [33mbcbio.variation.ensemble.intersect/get-rep-vc/[1;33mfn[m  [32m                    intersect.clj:   50[m
                                               [33mclojure.core/comp/[1;33mfn[m  [32m                         core.clj: 2438[m
                                                [33mclojure.core/map/[1;33mfn[m  [32m                         core.clj: 2624[m
                                          [37mclojure.lang.LazySeq.sval[m  [32m                     LazySeq.java:   40[m
                                           [37mclojure.lang.LazySeq.seq[m  [32m                     LazySeq.java:   49[m
                                                [37mclojure.lang.RT.seq[m  [32m                          RT.java:  507[m
                                                   [33mclojure.core/[1;33mseq[m  [32m                         core.clj:  137[m
                                                [33mclojure.core/map/[1;33mfn[m  [32m                         core.clj: 2616[m
                                          [37mclojure.lang.LazySeq.sval[m  [32m                     LazySeq.java:   40[m
                                           [37mclojure.lang.LazySeq.seq[m  [32m                     LazySeq.java:   49[m
                                             [37mclojure.lang.Cons.next[m  [32m                        Cons.java:   39[m
                                               [37mclojure.lang.RT.next[m  [32m                          RT.java:  674[m
                                                  [33mclojure.core/[1;33mnext[m  [32m                         core.clj:   64[m
                [33mbcbio.variation.variantcontext/[1;33mwrite-vcf-w-template[m  [32m               variantcontext.clj:  189[m
                                         [37mclojure.lang.RestFn.invoke[m  [32m                      RestFn.java:  573[m
                [33mbcbio.variation.ensemble.intersect/ensemble-vcfs/[1;33mfn[m  [32m                    intersect.clj:   87[m
                   [33mbcbio.variation.ensemble.intersect/[1;33mensemble-vcfs[m  [32m                    intersect.clj:   85[m
                           [33mbcbio.variation.ensemble.intersect/[1;33m-main[m  [32m                    intersect.clj:  139[m
                                        [37mclojure.lang.RestFn.applyTo[m  [32m                      RestFn.java:  137[m
                                                 [33mclojure.core/[1;33mapply[m  [32m                         core.clj:  630[m
                                  [33mbcbio.variation.recall.main/[1;33m-main[m  [32m                         main.clj:   33[m
                                        [37mclojure.lang.RestFn.applyTo[m  [32m                      RestFn.java:  137[m
                                   [37mbcbio.variation.recall.main.main[m  [32m                                 :     [m

' returned non-zero exit status 1

**Comment by chapmanb** [comment] 2015-11-04 02:08
Thanks for the report and apologies about the issue. The error message comes from trying to read the tabix index on one of the input files. It's hard to tell if this is from some kind of out of bounds call coming from bcbio, or an issue with an input file. It would be worth checking if the files (and their `.tbi` tabix indexes) look correct:
```
./project/work/freebayes/WT164-effects-ploidyfix-filter.vcf.gz 
./project/work/gatk-haplotype/WT164-effects-ploidyfix-combined-gatkclean.vcf.gz 
./project/work/samtools/WT164-effects-ploidyfix-filter.vcf.gz
```
Reading the bcbio.variation.recall code, I'm not sure how we'd go off of an index here since we're trying to pull a variant from each file in a called region, so these all should be within the genome boundaries. That being said, I've never run ensemble calling on mouse so am not sure if there are edge cases we're missing.

If fixing tabix indexes doesn't help, I'd be happy to debug more if you can reduce to a reproducible error case. Hope this helps some.

**Comment by lpantano** [comment] 2016-06-23 16:40
Closing this since it seems Brad suggestion worked.

thanks so much for using bcbio.

**Closed by lpantano** 2016-06-23 16:40 UTC
