### ISSUE TITLE
Rerunning with a different BED file for QC

### ISSUE THREAD

**Issue by vladsaveliev** [chapmanb/bcbio-nextgen#1710] opened 2016-12-22 22:06 UTC
There is a common scenario when a user wants to rerun QC with a different `coverage` BED file. Very often in AZ, Bcbio was run with some generic exome BED file set as `coverage` in yaml, and later they find a real capture target file from vendor and want to rerun only QC. 

Currently there is too many stuff they need to clean in the `work` directory in order to do that: coverage statistics files are located in `align`, `coverage`, `qc`, `bedprep`, `sambamba`, and `multiqc`. I mistakenly created a separate high-level folder for sambamba; it can easily go into `coverage` instead. Maybe `multiqc` might go to `qc`, and statistics for `align` might merge with `coverage` or `qc`. 

What do you think about this issue, and is it fine at all to rearrange folders in `work` because it might break user's reruns?

**Comment by lpantano** [comment] 2016-12-22 22:38
Hi,

The coverage calculated for each sample as it was coming from the piece of code I introduced is in `qc/sample/coverage`.  I was just following the logic of stats for each sample as it is for fastqc, etc. I don't mind to move that part to other place.

So, I think is ok if we put coverage files in `coverage` folder although I would keep the input of multiqc to create the coverage plots inside `qc/samples` because that would be in the final directory together with the rest of qc output.

About `multiqc`, it is outside QC, just because inside `qc` only there are the samples. But I don't think it would be a problem now that we pass multiqc directly the files location. multiqc there or inside `qc`, I don't know if it matters a lot, since in the `final` directory will be inside the `project` folder. 

But, yeah, moving that it would create incompatibility during a while, but this always happens, maybe it is just to coordinate with Brad to do this and quickly get a release after making sure everything works. 

Just my 2 cents.

**Comment by vladsaveliev** [comment] 2016-12-22 23:05
Thanks Lorena for your input and explanations. I didn't think about `qc` folder as one that goes entirely into `final` and is split across `sample/qc`, and for me it makes sense to keep it consistent this way.

So my vision of the `work` folder is the following:
- move all `bed` and `yaml` files from `align/*/` into `coverage`,
- move `sambamba` into `coverage`,
- move `multiqc` into `qc`.

After that, a user will have to clean up the following in order to rerun QC with another `coverage` file:
- `rm bedprep/cov-*` - bed file clean up work files
- `rm coverage/*/coverage_*` - work files related to coverage calculation
- `rm -rf qc` - all that QC output that further goes into `final`

**Comment by ohofmann** [comment] 2016-12-22 23:15
Something we'd discussed in the past was to have two different coverage calculations -- one standard one to assess global coverage (WGS, or all exome-target regions, etc.) to assess how the experiment worked in general, and a second more specific one for genes of (clinical) interest such as cancer drivers or ACMG. A single metric might also work for the latter coverage chart, e.g., something such as http://biorxiv.org/content/early/2016/05/24/051490 (percent of target nucleotides covered with N Q20 bases).

**Comment by chapmanb** [comment] 2016-12-23 02:47
Vlad -- thanks for the suggestions. I agree that your cleaned up suggestion sounds good, but the issue is that this will force users to have to re-run all of these coverage files if they restart or continue an older project, so it's pretty painful to make changes like this. I think we should do for recent changes like sambamba and quicker runing tools like multiqc, but should hold off on moving align/*/ coverage files over. So I'm up for points 2 and 3, just not 1.

I'd like to re-work coverage soon to see about generating CNV and QC metrics at the same time as the initial run so that might be an opportune time to explore moving those over to have everything cleaned up. Would that work?

Oliver, agree this would be nice to have and we could definitely do. Right now we have separate calculations of priority regions and coverage regions but I'd like to re-purpose the priority regions parts to do coverage on a separate set of standard targets of the users choice.

**Comment by vladsaveliev** [comment] 2016-12-23 10:47
Thanks Brad for you input, I absolutely agree about putting 1 aside until more major changes in coverage calculations are implemented.

**Comment by lpantano** [comment] 2017-05-06 21:59
Hi @vladsaveliev 

I will close this because a lot of changed since. Please, open a new issue if we are still missing something.

Thanks!

**Closed by lpantano** 2017-05-06 21:59 UTC
