### ISSUE TITLE
speedseq (lumpy) segmentation error

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#927] opened 2015-07-07 12:35 UTC
Hi - After reinstallation (#924) of lumpy I am not able to run it. To check that it is not because of 'restarting' the pipeline, I just ran other samples and got the same error - see below. 

The actual program that seems to fail is `speedseq` and it is in version 0.0.1. I did not find any bug reports in the speedeq repository.

Do you have any idea what the problem could be? Is speedseq preceeding or or succeeding lumpy or called by lumpy?

```
# call lumpy
/home/mpschr/bin/bcbionextgen/tools/bin/lumpy -t /home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_20
14_07_triotest-sort-bPE08_REL-svs -mw 4 -tt 0 -x /home/mpschr/Documents/projects/exon/scratch_PE08/structural/PE08_R
EL/lumpy/3_2014_07_triotest-sort-bPE08_REL-svs.sv-exclude.bed  -pe bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_REL/3_2014_07_triotest-sort-disc.bam,histo_file:/home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_2014_07_triotest-sort.bam.x4.histo,mean:177.821258192,stdev:58.5176621083,read_length:101,min_non_overlap:101,discordant_z:5,back_distance:10,weight:1,id:10,min_mapping_threshold:20 -pe bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_CR/1_2014_07_triotest-sort-disc.bam,histo_file:/home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/1_2014_07_triotest-sort.bam.x4.histo,mean:177.872711176,stdev:59.8641164274,read_length:101,min_non_overlap:101,discordant_z:5,back_distance:10,weight:1,id:20,min_mapping_threshold:20  -sr bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_REL/3_2014_07_triotest-sort-sr.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:11,min_clip:20 -sr bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_CR/1_2014_07_triotest-sort-sr.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:21,min_clip:20 > /home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_2014_07_triotest-sort-bPE08_REL-svs.sv.bedpe

/home/mpschr/bin/bcbionextgen/tools/bin/speedseq: line 989: 31118 Segmentation fault      (core dumped) $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING $LUMPY_SPL_STRING > $TEMP_DIR/$OUTBASE.sv.bedpe
' returned non-zero exit status 139

```

**Comment by chapmanb** [comment] 2015-07-08 05:13
Michael;
Sorry about the issues -- I'm not sure what is going on but it looks like a lumpy error on your input file. The chain of program calls here is bcbio -> speedseq -> lumpy, but you might be able to reproduce without all this by calling:
```
/home/mpschr/bin/bcbionextgen/tools/bin/lumpy -t /home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_2014_07_triotest-sort-bPE08_REL-svs -mw 4 -tt 0 -x /home/mpschr/Documents/projects/exon/scratch_PE08/structural/PE08_REL/lumpy/3_2014_07_triotest-sort-bPE08_REL-svs.sv-exclude.bed  -pe bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_REL/3_2014_07_triotest-sort-disc.bam,histo_file:/home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_2014_07_triotest-sort.bam.x4.histo,mean:177.821258192,stdev:58.5176621083,read_length:101,min_non_overlap:101,discordant_z:5,back_distance:10,weight:1,id:10,min_mapping_threshold:20 -pe bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_CR/1_2014_07_triotest-sort-disc.bam,histo_file:/home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/1_2014_07_triotest-sort.bam.x4.histo,mean:177.872711176,stdev:59.8641164274,read_length:101,min_non_overlap:101,discordant_z:5,back_distance:10,weight:1,id:20,min_mapping_threshold:20  -sr bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_REL/3_2014_07_triotest-sort-sr.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:11,min_clip:20 -sr bam_file:/home/mpschr/Documents/projects/exon/scratch_PE08/align/PE08_CR/1_2014_07_triotest-sort-sr.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:21,min_clip:20 > /home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_2014_07_triotest-sort-bPE08_REL-svs.sv.bedpe
```
If you're able to reproduce and simplify that to a smaller test case, I could try to reproduce and report upstream to the lumpy folks to determine the underlying cause. Sorry to not have a definite answer but hope this helps move forward.

**Comment by mpschr** [comment] 2015-07-08 05:55
This is the same call as the one I posted and caused the exception, correct? If I try to run it now, I run into the problem that the temporary folder `tx/tmpXKLK8B` does not exist anymore - so no input files. 

Is that a consequence of the speedseq-crash or the caues?

**Comment by chapmanb** [comment] 2015-07-08 06:03
Michael -- sorry I should have specified. You'll need to make a temporary directory to write to, since bcbio normally does that for you. You can either do that in the same directory that command wants or create it somewhere else and adjust the path in the command. Hope this helps.

**Comment by mpschr** [comment] 2015-07-08 06:09
Hi Brad. Ok - did not realize that they were files to write (instead of read). In any case, there is still a file missing. Upon executing the command (with the temp dir created), I get the following output:
```
Could not open /home/mpschr/Documents/projects/exon/scratch_PE08/tx/tmpXKLK8B/3_2014_07_triotest-sort.bam.x4.histo
Segmentation fault (core dumped)
```

So this file should already be there upon running the command?

**Comment by chapmanb** [comment] 2015-07-09 07:27
Michael;
Sorry, I should have realized that as well. I'm at the Bioinformatics Open Source Conference this week so not thinking fully and trying to answer in between managing that. Sorry for the confusion.

I thought more about this and worked on reproducing and am a bit confused regarding #924. lumpy shouldn't compile against an external bamtools, so not sure why you're getting that error at all. What does:
```
ldd /home/mpschr/bin/bcbionextgen/tools/bin/lumpy
```
Mine does not have an external library dependency to libbamtools. What type of system are you compiling on?

Also, to check if it is an issue with lumpy or with your input file, could you try editing this test file in a local GitHub checkout to be `svcaller: lumpy`:

https://github.com/chapmanb/bcbio-nextgen/blob/c4b52db61b84cee9224962990d5c9c464e91b30a/tests/data/automated/run_info-bam.yaml#L34

then running the test:
```
cd tests
./run_tests.sh devel
```
if that works cleanly we can rule out an issue with lumpy itself and will have to look more into how you produced the BAM file you're using for SV calling to see if that is causing issues with lumpy.

Hope this helps give some ideas for debugging.

**Comment by mpschr** [comment] 2015-07-09 15:12
Hi @chapmanb 

I don't think it compiled against any external tools. Here is the output:

```
ldd /home/mpschr/bin/bcbionextgen/tools/bin/lumpy
	linux-vdso.so.1 =>  (0x00007ffea7cdb000)
	libbamtools.so.2.4.0 => /home/mpschr/bin/bcbionextgen/tools/lib/libbamtools.so.2.4.0 (0x00007faf69d9a000)
	libz.so.1 => /home/mpschr/bin/bcbionextgen/tools/lib/libz.so.1 (0x00007faf69b87000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faf69983000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faf69765000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faf69461000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faf6915b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faf68f45000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faf68b80000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faf69ff7000)

```

Regarding the test run. It seems as lumpy is also failing there, with the same error:

```
[2015-07-09T15:09Z] INFO  17:09:23,296 logging$eval36$fn__42 - State :finished :: {:desc "Finished"}
[2015-07-09T15:09Z] Timing: ensemble calling
[2015-07-09T15:09Z] Timing: validation summary
[2015-07-09T15:09Z] Timing: structural variation final
[2015-07-09T15:09Z] multiprocessing: detect_sv
[2015-07-09T15:09Z] speedseq lumpy : Test1
[2015-07-09T15:09Z] Sourcing executables from /home/mpschr/bin/bcbionextgen/tools/bin/speedseq.config ...
[2015-07-09T15:09Z] Calculating alignment stats... sambamba-view:  (Broken pipe)
[2015-07-09T15:09Z] Removed 0 outliers with isize >= 411
[2015-07-09T15:09Z] done
[2015-07-09T15:09Z] Running LUMPY...
[2015-07-09T15:09Z] 
[2015-07-09T15:09Z] # call lumpy
[2015-07-09T15:09Z] /home/mpschr/bin/bcbionextgen/tools/bin/lumpy -t /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z/Test1-sort-TestBatch1-svs -mw 4 -tt 0 -x /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/structural/Test1/lumpy/Test1-sort-TestBatch1-svs.sv-exclude.bed  -pe bam_file:/home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort-disc.bam,histo_file:/home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z/Test1-sort.bam.x4.histo,mean:152.8900392,stdev:31.4103339138,read_length:76,min_non_overlap:76,discordant_z:5,back_distance:10,weight:1,id:10,min_mapping_threshold:20  -sr bam_file:/home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort-sr.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:11,min_clip:20 > /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z/Test1-sort-TestBatch1-svs.sv.bedpe
[2015-07-09T15:09Z] 
[2015-07-09T15:09Z] 210	0
[2015-07-09T15:09Z] /home/mpschr/bin/bcbionextgen/tools/bin/speedseq: line 989: 31893 Segmentation fault      (core dumped) $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING $LUMPY_SPL_STRING > $TEMP_DIR/$OUTBASE.sv.bedpe
[2015-07-09T15:09Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/home/mpschr/bin/bcbionextgen/data/anaconda/bin:$PATH && speedseq sv -v -B /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort.bam -S /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort-sr.bam -D /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort-disc.bam -R /home/mpschr/Documents/projects/bcbio-nextgen/tests/data/genomes/hg19/seq/hg19.fa -x /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/structural/Test1/lumpy/Test1-sort-TestBatch1-svs.sv-exclude.bed -A false -T /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z -o /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/30cef89d-fe58-404e-b009-a3ef566af31a/tmpPP0AI2/Test1-sort-TestBatch1-svs
Sourcing executables from /home/mpschr/bin/bcbionextgen/tools/bin/speedseq.config ...
Calculating alignment stats... sambamba-view:  (Broken pipe)
Removed 0 outliers with isize >= 411
done
Running LUMPY... 

# call lumpy
/home/mpschr/bin/bcbionextgen/tools/bin/lumpy -t /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z/Test1-sort-TestBatch1-svs -mw 4 -tt 0 -x /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/structural/Test1/lumpy/Test1-sort-TestBatch1-svs.sv-exclude.bed  -pe bam_file:/home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort-disc.bam,histo_file:/home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z/Test1-sort.bam.x4.histo,mean:152.8900392,stdev:31.4103339138,read_length:76,min_non_overlap:76,discordant_z:5,back_distance:10,weight:1,id:10,min_mapping_threshold:20  -sr bam_file:/home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1-sort-sr.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:11,min_clip:20 > /home/mpschr/Documents/projects/bcbio-nextgen/tests/test_automated_output/tmptest/bcbiotx/17d9fcf2-55e7-4fd1-bc31-8c1a1cadfa0d/tmpRh627z/Test1-sort-TestBatch1-svs.sv.bedpe
        
210	0
/home/mpschr/bin/bcbionextgen/tools/bin/speedseq: line 989: 31893 Segmentation fault      (core dumped) $LUMPY -t ${TEMP_DIR}/${OUTBASE} -mw $MIN_WEIGHT -tt $TRIM_THRES $EXCLUDE_BED_FMT $LUMPY_DISC_STRING $LUMPY_SPL_STRING > $TEMP_DIR/$OUTBASE.sv.bedpe
' returned non-zero exit status 139

```

**Comment by chapmanb** [comment] 2015-07-10 05:16
Michael;
Thanks for this debugging. This helps a lot. I'm specifically worried about the lumpy binary linking against bamtools 2.4.0:
```
ldd /home/mpschr/bin/bcbionextgen/tools/bin/lumpy
    libbamtools.so.2.4.0 => /home/mpschr/bin/bcbionextgen/tools/lib/libbamtools.so.2.4.0 (0x00007faf69d9a000)
```
which my local build does not do. lumpy has an internal bamtools included for the compilation and I'm worried it might not be compatible with 2.4.0. Could you try doing this:
```
brew uninstall --force bamtools
brew uninstall --force lumpy-sv
brew install lumpy-sv --ignore-dependencies
brew install bamtools --ignore-dependencies
```
and see if `ldd /path/to/lumpy` is still linking against the 2.4.0 shared library. If not, it would be helpful to know if this resolves the issue with the test case. 

Fingers crossed this will help. I wish I could reproduce the issue locally. If this is still broken, it would help to know what type of system you're running this on and I can try to dig further. Thanks again for the patience debugging,

**Comment by mpschr** [comment] 2015-07-10 05:56
Hi Brad

Now I understand - lumpy has its own bamtools binary? In your case, where is it located? If not in this folder `{bcbionextgen-install-folder}/tools/lib/`? 

It could be that it finds the shared libbamtool.so first or the other not at all and compiles against that one. 

I will do a reinstall as soon the current run is over and report back.

**Comment by chapmanb** [comment] 2015-07-11 05:59
Michael;
In my case, lumpy doesn't dynamically link against bamtools. I believe it's statically compiled against the bamtools library included with the lumpy distribution:

https://github.com/arq5x/lumpy-sv/blob/2de8275adf457196695bb8f413e3354e4cc1673e/Makefile#L50

I was curious about your environment and library path setup to see why it dynamically links in your case and not in mine. Hope the reinstall helps some.

**Comment by mpschr** [comment] 2015-07-13 08:47
Hi @chapmanb. Indeed, I do not get a segmentation fault anymore and it seems that lumpy is being run. Thanks for that!

Any how I get another error from the awk code:

```
# convert to VCF, ensure that each variant has at least one sample with MIN_WEIGHT support
cat /home/mpschr/Documents/projects/exon/scratch_PE02/tx/tmpM5euLW/2_PE03_hirvi20150709-sort-bPE03_REL-svs.sv.bedpe \
    | /home/mpschr/bin/bcbionextgen/tools/bin/bedpeToVcf -t LUMPY -c /home/mpschr/Documents/projects/exon/scratch_PE02/
tx/tmpM5euLW/2_PE03_hirvi20150709-sort-bPE03_REL-svs.sample.config -f /home/mpschr/bin/bcbionextgen/data/genomes/Hsapie
ns/GRCh37/seq/GRCh37.fa \
    | awk -v MIN_WEIGHT=4 'BEGIN {S_IDX=0} {
        if (/home/mpschr/bin/bcbionextgen/tools/bin/speedseq~"^#") print
        else {
            if (S_IDX==0) {
                split(/home/mpschr/bin/bcbionextgen/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa,fmt,":");
                for (i=1;i<=length(fmt);++i) {
                    if (fmt[i]=="SUP") S_IDX=i
                }   
            }
            else {  
                PASS=0
                for (i=10;i<=NF;++i) {
                    split(1,a,":");
                    if (a[S_IDX]>=MIN_WEIGHT) PASS=1;
                }   
            }
        }
        if (PASS) print
    }' \
    > /home/mpschr/Documents/projects/exon/scratch_PE02/tx/tmpM5euLW/2_PE03_hirvi20150709-sort-bPE03_REL-svs.sv.vcf

awk: line 6: illegal reference to array fmt
cat: write error: Broken pipe
' returned non-zero exit status 2
```

Should I open a separate issue for that?

**Comment by chapmanb** [comment] 2015-07-13 11:12
Michael;
Sorry about the issues. I'm honestly not sure what is going on with awk here. Practically, I've been meaning to move to the new simplified `lumpyexpress` approach which will no longer rely on speedseq and should hopefully make this less painful. I submitted a PR to homebrew-science to update lumpy to the latest version that supports this: https://github.com/Homebrew/homebrew-science/pull/2515

Once that gets pulled, I'll update bcbio to use lumpyexpress instead of speedseq and I hope that will give you a cleaner experience. We can continue to track the issue here and I'll give you an update as soon as that gets pulled and we can check in the changes on the bcbio side.

Sorry about all the problems here. I hope the new simplified workflow will be cleaner for you.

**Comment by mpschr** [comment] 2015-07-13 11:48
Hi @chapmanb 

It seems like the second issue was an awk issue. As described at stackoverflow (http://stackoverflow.com/questions/16921493/awk-illegal-reference-to-array-a), I changed the for routine of the `speedseq`  binary to the propesed format and now it seems that it is running. So really it's a speedeq issue on Ubuntu Linux it seems

**Comment by mpschr** [comment] 2015-07-13 12:20
By the way, I will be happy to test the `lumpyexpress` solution

**Comment by chapmanb** [comment] 2015-07-15 13:31
Michael;
Glad the local awk change got things working for you. The lumpy update got pulled into homebrew-science and I just pushed the changes to use lumpyexpress instead of speedseq. Hopefully this'll work more cleanly for you -- please let me know if you run into any other issues at all. Thanks again for the help debugging.

**Comment by chapmanb** [comment] 2015-07-15 13:52
Michael;
Sorry, a bit too quick on asking for testing. @mjafin ran a test case with this and found issues with the output file sorting of the VCF from lumpy. I'll work on resolving this first before asking for help testing. Sorry for the extra radio traffic.

**Comment by chapmanb** [comment] 2015-07-18 04:16
Michael -- Lumpy should be working correctly now with `lumpyexpress` in the latest development version. If you update with `bcbio_nextgen.py upgrade -u development --tools` it should not provide a cleaner run without speedseq and hopefully work without any adjustments. Thanks again for all the reports and testing.

**Comment by mpschr** [comment] 2015-07-23 06:31
Hi Brad - My computing power is a bit swamped at the moment - I hope to give it a try next week! Just out of curiosity. But if the lumpyexpress does not reliy on awk for loops then there should be no problem

**Comment by lpantano** [comment] 2016-06-23 20:31
I hope that fixed the issue, if still you have problem let us know and feel free to re-open.

thanks!

**Closed by lpantano** 2016-06-23 20:31 UTC
