### ISSUE TITLE
Issues rendering the R report

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1122] opened 2015-11-26 08:55 UTC
Currently there are several issues rendering the R report. I moved into the `report` directory, which BTW stays in `work` and not in the directory where `upload` has set and issued:

```r
library(rmarkdown)
rmarkdown::render("report-ready.Rmd")
```

This errors immediately because `path_results` in the report file is an absolute path. It should be a relative path (use case: I'm moving files out of the cluster on my own machine).

The second error is an actual rendering error:

```r
  |.........................................                        |  64%
label: completeness-fig (with options) 
List of 3
 $ fig.height: num 12
 $ fig.width : num 12
 $ cache     : logi TRUE

Quitting from lines 301-303 (report-ready.Rmd) 
Error in as.matrix(d[, c("percentage10", "percentage20", "percentage50")] >  : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
   'dimnames' [2] length not equal to array extent
````

And what `traceback()` gives me:

````r
18: as.matrix(d[, c("percentage10", "percentage20", "percentage50")] > 
        60) at <text>#18
17: get_quantile_cov(file.path(path_results, "coverage"))
16: eval(expr, envir, enclos)
15: eval(expr, envir, enclos)
14: withVisible(eval(expr, envir, enclos))
13: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler, 
        error = eHandler, message = mHandler)
12: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir, 
        enclos)), warning = wHandler, error = eHandler, message = mHandler))
11: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos, 
        debug = debug, last = i == length(out), use_try = stop_on_error != 
            2L, keep_warning = keep_warning, keep_message = keep_message, 
        output_handler = output_handler)
10: evaluate::evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), 
        keep_message = !isFALSE(options$message), stop_on_error = if (options$error && 
            options$include) 0L else 2L, output_handler = knit_handlers(options$render, 
            options))
9: in_dir(opts_knit$get("root.dir") %n% input_dir(), evaluate::evaluate(code, 
       envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), 
       keep_message = !isFALSE(options$message), stop_on_error = if (options$error && 
           options$include) 0L else 2L, output_handler = knit_handlers(options$render, 
           options)))
8: block_exec(params)
7: call_block(x)
6: process_group.block(group)
5: process_group(group)
4: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
       error = function(e) {
           setwd(wd)
           cat(res, sep = "\n", file = output %n% "")
           message("Quitting from lines ", paste(current_lines(i), 
               collapse = "-"), " (", knit_concord$get("infile"), 
               ") ")
       })
3: process_file(text, output)
2: knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet, 
       encoding = encoding)
1: rmarkdown::render("report-ready.Rmd")
```

**Comment by lbeltrame** [comment] 2015-11-26 09:18
The problem is that some coverage files are empty, but loaded, and thus R bombs when trying to asssemble them.

Skipping files isn't an option, given that now there are incompatible dimensions.

**Comment by lbeltrame** [comment] 2015-11-26 11:09
In fact even trying to fix this yields several errors, including typos which prevent this from running at all:

In `get_quantile_cov`:

````r
 ma = ma + (d[,c("percentage10", "percentage20", "percentage50")] > 60 * 1)
````
Shouldn't it be like the row under, which is

````r
 ... > 60) * 1
````

**Comment by lbeltrame** [comment] 2015-11-26 11:25
Should I file separate issues for each rendering error? Because for now I've found at least 3 different issues:

1. `get_quantile_cov` breaks on empty files (why they're empty is a different matter)
2. `table-variants` uses columns that *aren't* in the metric.tsv files (`sample` and `Variations_in_dbSNP_pct`)
3. `gc-depth-parse` fails with "more columns than column names" because the files (`*-depth-parse.tsv`) have more columns than the header.

**Comment by chapmanb** [comment] 2015-11-26 11:53
Luca;
No need for multiple reports, this is great. I'm sure Lorena and Rory will take a look after the Thanksgiving holiday weekend here. Sorry I don't know a ton about the coverage reporting magic to answer right away. Practically, are you running the latest development? I know there have been a number of fixes that went in since the last release so upgrading might resolve these. Hope this helps some.

**Comment by lpantano** [comment] 2015-11-26 14:51
Hi lucas, 

thanks for all the report.

could you tell me the version of bcbreport in the bcbio python installation? Some of this errors I remember to fix it, but maybe I forgot to bump the version.

will work on that during these days.

**Comment by lpantano** [comment] 2015-11-26 14:53
as well, report should be in the final directory: https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/upload/__init__.py#L360 it should be in the project folder inside the final folder. It worked in the test, will try to reproduce with other data set.

**Comment by lpantano** [comment] 2015-11-26 16:01
Hi Lucas,

I fix the multiple columns in the GC file, it happens in tumor/normal analysis. I tried to skip the empty files, but need to work on that to check that fully works.
Still have to look at the variation_in_dbsnp and sample columns since I cannot reproduce.

I change the path to set the current path in R, so you will need always to set the path to the Rmd file before render. Anyway there is not a general solution, because other would want to copy the file to other place but not the files with the data, I put that variable there just to allow an easy way to change where files were without mess with everything. So, sorry to not have a universal solution right now.

thanks for your help.

**Comment by lpantano** [comment] 2016-04-24 23:14
Hi,

I will close this, since at least at this point  it seems that part works. Feel free to open another if you find further issues (I am sure there will be :) ) thanks!

**Closed by lpantano** 2016-04-24 23:14 UTC
