### ISSUE TITLE
Small RNA pipeline - issue with tdrmapper

### ISSUE THREAD

**Issue by AurelieMLB** [chapmanb/bcbio-nextgen#1352] opened 2016-04-20 09:50 UTC
Hello,

My understanding was that there should be a mapping to known tRNA using tdrmapper (http://bcbio-nextgen.readthedocs.org/en/latest/contents/pipelines.html#smallrna-seq) and that there should be a folder in final or inside sample folders. 
After I tried to run the pipeline, I cannot find this folder at all.
I did search for tdrmapper in the nohup.out in the work folder it seems that there is no mention of it. So it is like the pipeline was not trying to launch it at all.
Yet there is a TdrMappingScripts.pl in the bcbio app folder that we have... 
In the work folder of my run, I do have a trna folder which seems to give the mapping for each samples. I am not sure it is the expected output of tdrmapper compared to this.

Many thanks for any help

**Comment by lpantano** [comment] 2016-04-24 23:06
Hi, will close this since the problem is the same than #1353. Thanks for the detailed information.

**Closed by lpantano** 2016-04-24 23:06 UTC
