### ISSUE TITLE
miRDeep2 step in small RNA pipeline crashes on A.thaliana reference

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1421] opened 2016-06-06 20:38 UTC
Hi!

I'm running small RNA pipeline on A.thaliana (TAIR10). 
It exits on the miRDeep2 step:
```
#Starting miRDeep2
Error: Genome file [some_path]/bcbio/genomes/Athaliana/TAIR10/seq/TAIR10.fa has not allowed whitespaces in its first identifier
```
The reference was installed with bcbio, not manually.
I see that it does not like whitespaces in the reference, but I'm not sure how the other tools would react if I change the file. Any ideas to fix, or at least how to turn this step off?

Many thanks.
SN

**Comment by lpantano** [comment] 2016-06-07 15:09
Hi @naumenko-sa 

sorry about this. Let me modify mirdeep2 and update the tool so you can finish this. If you are in a hurry, you can remove the `mirdeep2-fasta` line in the resources file of the genome, and will skip it. I will try to fix this for today though.

thanks

**Comment by naumenko-sa** [comment] 2016-06-07 18:50
Thank you for the quick response! I would be happy to run it tomorrow! Good luck with fixing and let me now when to update. SN

**Comment by lpantano** [comment] 2016-06-08 02:49
you can update tools and try again. It should handle whitespaces now.

let me know if that works

sent not from my computer

**Comment by naumenko-sa** [comment] 2016-06-08 15:40
Thanks, it has passed that point.
Now it exits on 
```
No file mirdeep_runs/run_res/tmp/precursors.fa_stack found
' returned non-zero exit status 2
```
Last command from bcbio-nextgen-debug is 
```
#excising precursors
started: 11:32:14
/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/mirdeep2//excise_precursors_iterative_final.pl /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Athaliana/TAIR10/seq/TAIR10.fa mirdeep_runs/run_res/tmp/align.bam_parsed.arf mirdeep_runs/run_res/tmp/precursors.fa mirdeep_runs/run_res/tmp/precursors.coords 50000
#excising precursors
1	209402
2	209402
3	209402
4	209402
5	209402
6	209402
7	209402
8	209402
9	209402
10	201258
11	194088
12	189996
13	184670
14	179524
15	175600
16	171496
17	167730
18	164474
19	161312
20	158216
21	155248
22	152704
23	150152
24	147680
25	145366
26	143142
27	141106
28	139034
29	137086
30	135302
31	133666
32	131854
33	130242
34	128572
35	127008
36	125500
37	124006
38	122706
39	121320
40	119992
41	118532
42	117230
43	115982
44	114846
45	113760
46	112456
47	111328
48	110226
49	109158
No file mirdeep_runs/run_res/tmp/precursors.fa_stack found
' returned non-zero exit status 2
```

**Comment by lpantano** [comment] 2016-06-08 19:29
Hi,

I think is better to skip mirdeep2 at this point, since actually is not well known how works with non-animal species.

You need to update the genome data and it should do the trick.

I will try to get some data to try to reproduce this issue.

thanks

**Comment by naumenko-sa** [comment] 2016-06-08 20:52
At some point the pipeline stopped producing fastqc reports. (Because I've commented mirdip2-fasta line in the TAIR10-resources.yaml?).

**Comment by lpantano** [comment] 2016-06-09 13:43
Hi,

thanks for the report. It seems that something happened when we change the logic in the QC step. I pushed a fix to get the fastqc again for all samples in the smallRNAseq pipeline.

thanks!

**Comment by naumenko-sa** [comment] 2016-06-09 17:47
Many thanks, I re-run the whole analysis, it works! The current version is much stable than previous: my other analyses of variant calling with exomes are now running well (they were crashing with multiqc before). By the way, we turned off seqcluster with tools_off, and mirdeep2 with TAIR10-resources.yaml. Isn't it better to do both in the same way with tools_off?

**Comment by lpantano** [comment] 2016-06-09 22:30
Hi,

sorry about the mess. I am trying to think the best way to 'fix' this. I think in this case is correct to do it at genome annotation level since we don't know how mirdeep2 works. The idea of the pipeline is to use all the tools available for different sections, although that means more possible errors.

I am thinking in a way to divide the pipeline in functional annotation, like miRNA, novel discovery, clusters over genome, and give set of tools options. Then, each part will run only if there is a tool listed in the YAML file.

Mainly that is the future plan.

thanks for helping getting the pipeline working with other species.

**Comment by lpantano** [comment] 2016-06-10 14:24
Hi, 

I pushed a new way to specify what tools to use. Hope this helps to get to cleaner run. I will try to add plant mirna de novo discovery.

cheers

**Closed by lpantano** 2016-06-10 14:24 UTC

**Comment by naumenko-sa** [comment] 2016-06-10 14:38
Thanks!
