### ISSUE TITLE
Installing Data

### ISSUE THREAD

**Issue by alexstaj** [chapmanb/bcbio-nextgen#906] opened 2015-06-26 20:35 UTC
Greetings

I successfully installed hg38 with aligners, bowtie, bwa, bowtie2, and star.  I now tried to install mm10 with all the same aligners and ran into this:

INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome mm10 with index star
INFO: Preparing genome mm10 with index star
[localhost] local: mkdir /usr/local/share/bcbio/genomes/Mmusculus/mm10/star
[localhost] local: STAR --genomeDir /usr/local/share/bcbio/genomes/Mmusculus/mm10/star --genomeFastaFiles /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/mm10.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14
Jun 25 12:19:47 ..... Started STAR run
Jun 25 12:19:47 ... Starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

Fatal error: local() encountered an error (return code 134) while executing 'STAR --genomeDir /usr/local/share/bcbio/genomes/Mmusculus/mm10/star --genomeFastaFiles /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/mm10.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14'

Aborting.
INFO: Genome preparation method raw failed, trying next
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 254, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/staj/tools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/staj/tools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/staj/tools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 266, in configure_instance
    setup_biodata(options)
  File "/home/staj/tools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 248, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/staj/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 348, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/staj/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 486, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index star for mm10 by any method
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'mm10', '--aligners', 'bwa', '--aligners', 'bowtie2', '--aligners', 'bowtie', '--aligners', 'star', '--data']' returned non-zero exit status 1

**Comment by mpschr** [comment] 2015-06-26 23:44
I had the same problem - see issue chapmanb/cloudbiolinux#197 - and its because hg38 is not fully supported yet. Maybe it could give a warning or similar.

**Comment by lpantano** [comment] 2015-06-27 00:23
Hi @alexstaj,

sorry about that problem. Could you try to run the command alone: 

`
STAR --genomeDir /usr/local/share/bcbio/genomes/Mmusculus/mm10/star --genomeFastaFiles /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/mm10.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14
`

Does it fail at the moment? or dows it take a while?

if this gives an error as well, you can try removing `--sjdbGTFfile /usr/local/share/bcbio/genomes/Mmusculus/mm10/seq/../rnaseq/ref-transcripts.gtf` to make sure is not the gtf file the one with problems.

If this doesn't fix it, maybe the problem is the `genomeSAindexNbases 14`, although we created index with this values for mouse in the past.

**Comment by roryk** [comment] 2015-10-05 21:17
Closing this because it seems like it is okay. Hope this is straightened out @alexstaj , mm10 definitely should work so if this is still causing issues, feel free to reopen it.

**Closed by roryk** 2015-10-05 21:17 UTC
