### ISSUE TITLE
Issue: reproducibility of results between pipeline versions

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1067] opened 2015-10-19 14:41 UTC
While reanalyzing some results with the newest version of the pipeline and comparing them with an old revision (March 2014; version 0.7.8) I found what could be a possible issue with regards to reproducibility, at least using MuTect.

Here's an example on the same sample:

Old results: 

```
chr17   7578115 rs1625895       T       C       0       REJECT
```

New results:

```
chr17   7578115 rs1625895       T       C       .       PASS 
```

I've also seen the opposite: variants called with MuTect as `PASS` in the 2014 run will trigger a `REJECT` in the most recent versions.  This can be a pretty severe problem in case these data are used for publications.

**Comment by lbeltrame** [comment] 2015-10-19 18:52
I'm doing a couple of test runs with different sample combinations to rule out PEBKAC. I'll report back here.

**Comment by chapmanb** [comment] 2015-10-20 00:07
Luca;
Thanks for reporting the different results. The goal with bcbio is to maintain similar (or better) rates of sensitivity and precision by evaluating calling against standard benchmarks as we refactor and add new versions of tools, so users can upgrade across versions. It's not likely you'll have exactly identical results between bcbio versions a year and a half apart, but the target would be that they're close, or improved, in the later versions.

It would be useful to know how frequently you see this to get a sense of the underlying issue. If you can provide any reproducible sample cases where we call differently I'd also be happy to look at them.

In terms of exact reproducibility, the Docker container development is the approach we're following to achieve that. Since the containers capture bcbio code as well as the external tools, this makes it easier to lock down the entire set of operations so you could pull up a container and get identical results later.

Hope this helps some and happy to look more if you identify problems.

**Comment by lbeltrame** [comment] 2015-10-20 08:10
Luckily I have seen this just once for now, and funnily enough I get the "old" result if I use the current state of the pipeline: the issue seems to have surfaced somehow around April (that's where the "new" entry comes from), but given the fast pace of development (I track master) I'm not sure if I just caught a bad state of things or something. 

I ran different tests yesterday to rule out human error, bad files, etc., but now they are always consistent.  Hopefully I'll hit a small enough case that can be further investigated. 

If you don't mind, I could close the issue and perhaps open another one to track what's currently done to maximize reproducibility, so that interested parties can chime in with further suggestions.

**Comment by chapmanb** [comment] 2015-10-20 14:12
Sorry about the issue, I'm not sure what happened but glad to hear the latest works as expected. We can use this issue to discuss reproducibility and also happy to add details about this to the documentation if you want to summarize comments. Thanks for leading this discussion.

**Comment by lpantano** [comment] 2017-05-06 22:12
Hi @lbeltrame 

I will close this guessing everything is solved now. Let us know if you find more issues.

Thanks!

**Closed by lpantano** 2017-05-06 22:12 UTC
