### ISSUE TITLE
Reproducibility of variant calls

### ISSUE THREAD

**Issue by asalomatov** [chapmanb/bcbio-nextgen#834] opened 2015-04-24 16:24 UTC
Hi, 
I ran bcbio 3 times with identical settings, and using the same input ( a trio of bam files). Then I compared gatk-haplotype.vcf for all 3 runs with vcf-compare, please see below... Why so much variability from run to run?
Thanks.

```
# This file was generated by vcf-compare.
# The command line was: vcf-compare(r953) ../bcbio/testrun2/final_11480/project_2015-04-16/11480-gatk-haplotype.vcf.gz ../bcbio/testrun3/final_11480/project_2015-04-22/11480-gatk-haplotype.vcf.gz ../bcbio/testrun4/final_11480/project_2015-04-23/11480-gatk-haplotype.vcf.gz
#
#VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are:
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
VN      7       ../bcbio/testrun2/final_11480/project_2015-04-16/11480-gatk-haplotype.vcf.gz (4.7%)     ../bcbio/testrun3/final_11480/project_2015-04-22/11480-gatk-haplotype.vcf.gz (5.7%)     ../bcbio/testrun4/final_11480/project_2015-04-23/11480-gatk-haplotype.vcf.gz (17.1%)
VN      7       ../bcbio/testrun3/final_11480/project_2015-04-22/11480-gatk-haplotype.vcf.gz (5.7%)     ../bcbio/testrun4/final_11480/project_2015-04-23/11480-gatk-haplotype.vcf.gz (17.1%)
VN      10      ../bcbio/testrun2/final_11480/project_2015-04-16/11480-gatk-haplotype.vcf.gz (6.8%)     ../bcbio/testrun4/final_11480/project_2015-04-23/11480-gatk-haplotype.vcf.gz (24.4%)
VN      17      ../bcbio/testrun4/final_11480/project_2015-04-23/11480-gatk-haplotype.vcf.gz (41.5%)
VN      37      ../bcbio/testrun2/final_11480/project_2015-04-16/11480-gatk-haplotype.vcf.gz (25.0%)    ../bcbio/testrun3/final_11480/project_2015-04-22/11480-gatk-haplotype.vcf.gz (30.1%)
VN      72      ../bcbio/testrun3/final_11480/project_2015-04-22/11480-gatk-haplotype.vcf.gz (58.5%)
VN      94      ../bcbio/testrun2/final_11480/project_2015-04-16/11480-gatk-haplotype.vcf.gz (63.5%)
#SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN      Number of REF matches:  7
SN      Number of ALT matches:  7
SN      Number of REF mismatches:       0
SN      Number of ALT mismatches:       0
SN      Number of samples in GT comparison:     0
```

**Comment by chapmanb** [comment] 2015-04-24 17:44
Thanks for checking on the reproducibility of the runs. We're always interested in this. I don't know if I totally understand the output of vcf-compare but it looks like something is wrong. Why do you have so few variants in the output (on the order of 100)? Can you provide more details about the type of variant calling you're doing? Thanks again.

**Comment by asalomatov** [comment] 2015-04-24 18:17
I am looking at whole exome data. For testing purposes I down-sampled the bam files to .001 of their original size. Here are the config files https://www.dropbox.com/sh/ff84eibatyub1yn/AABL0pP11f2orDbRysxsyw6-a?dl=0

**Comment by chapmanb** [comment] 2015-04-24 18:43
Andrei;
Thanks for the additional information. I think I understand now. You downsampled the BAM files to very low coverage and then called, leaving with a low number of variants. My expectation is that most (maybe all) of these will be filtered due to lack of evidence. `vcf-compare` does not appear to remove filtered variants, it just compares everything. You'll want to pre-filter these before running the comparison with something like: `bcftools view -f 'PASS,.' orig.vcf.gz`. Hope that doing that will result in a better overlap/comparison.

**Comment by asalomatov** [comment] 2015-04-24 19:00
Hi Brad, thanks for a quick response, i'll check this on monday. But regardless of filtering, if inputs are the same, shouldn't outputs be the same, or very close to it?

**Comment by chapmanb** [comment] 2015-04-24 19:47
Andrei;
If these are low read depth, poorly supported, filtered variants I believe there is less guarantee that they'll be called consistently. I don't have a lot of experience with that kind of data so am only making guesses. If you'd like to investigate this more you might also want to turn off recalibration and realignment to see where potential sources of non-stochasticity come from. Hope this helps some.

**Comment by asalomatov** [comment] 2015-04-28 15:11
Brad,
I looked at the filtered files, and all but 2 or 3 variants have passed filter so low concordance remains. I do believe that down-sampling causes this behavior as I am not seeing this with full-size files. I'm testing bcbio against my own pipeline that goes through the same steps as bcbio, including base quality recalibration and indel realignment, and it gets consistent calls for reruns on down-sampled reads, but but generates about twice as many calls as bcbio.

**Comment by chapmanb** [comment] 2015-04-28 18:10
Andrei;
That's strange about the low-coverage calling. I don't have much experience doing this so am not sure what to make of it. If you can post a couple of discrepant runs it might be helpful to try and diagnose what is going on. If we can replicate outside of bcbio we could also ask about HaplotypeCaller run to run variability on the GATK forums.

Regarding your external run versus bcbio, I'm not sure why you are finding twice as many calls. If you can pull up some examples that could help. You could also validate your pipeline against the NA12878 genome in a bottle calls to see if the results look reasonable. We're also happy to tweak bcbio to improve sensitivity if we can maintain precision. Here's the most recent validation writeup for more details:

http://bcb.io/2014/10/07/joint-calling/

Thanks again for digging into these issues.

**Comment by asalomatov** [comment] 2015-04-29 22:26
Brad,
thanks for your interest. Here are bcbio gatk HC vcf files from two runs https://www.dropbox.com/sh/ikmnv3o0tnhrp5w/AAA2bVMW6U5Z5SKr14jeUHD6a?dl=0

and these (perfectly concordant) are from 2 runs of my pipeline (gatk HC) on the same data https://www.dropbox.com/sh/ctbchjcr20nsd65/AABoh1KwU0JyoarKasDeO9-6a?dl=0
I might be missing a filtering step somewhere in the process that would reduce number of calls, I'd appreciate any suggestion.

**Comment by chapmanb** [comment] 2015-04-30 13:41
Andrei;
Thanks much for these, this is a big help to think through the potential issues. I think the problem might be in how bcbio defines the callable regions. If you look at `regions/11480-analysis_blocks.bed` for the two runs, are they the same or different?

By default, bcbio tries to exclude low coverage regions with coverage of 4 or less from calling since they aren't reliable for calling homozygotes (much less heterozygotes). This is tunable for real low-pass calling but in practice that is not done especially often anymore. I don't expect the selection of these regions to be stochastic but could be missing something. That would explain why you see the calls in some samples and not others, since these all have low coverage with a median of 2 reads supporting calls.

I believe the selection of where to call would also explain why you see differences with your calling approach, which might not do this.

It would also help to try this with alignment instead of prepping the BAM files (so `aligner: bwa` instead of `aligner: false`). This could help identify if there is something in the BAM prep process causing issues.

Thanks for helping debug this. I'll keep digging into potential issues with the analysis region assignment.

**Comment by asalomatov** [comment] 2015-04-30 19:55
Brad,
analysis_blocs.bed files for both runs are identical.

**Comment by chapmanb** [comment] 2015-05-01 20:18
Andrei;
Thanks for checking this, I guess we can rule out my speculation about regions. As another step beyond this, do the calls for some of the problem regions that differ have the same command lines in `log/bcbio-nextgen-commands.log`. If you want to make those files available to me I can also dig at this. I'll also try to generate low sequence data to see if I can reproduce but any other clues from digging about where they might be different would be helpful in trying to narrow this down. Thanks for all the help debugging.

**Comment by asalomatov** [comment] 2015-05-05 16:13
Brad,
I added the log files... https://www.dropbox.com/sh/ikmnv3o0tnhrp5w/AAA2bVMW6U5Z5SKr14jeUHD6a?dl=0

**Comment by lpantano** [comment] 2017-05-06 22:15
Hi @asalomatov,

I will close this guessing you got it working. Let us know if you find more issues.

Thanks!

**Closed by lpantano** 2017-05-06 22:15 UTC
