### ISSUE TITLE
conda MD5 mismatch errors

### ISSUE THREAD

**Issue by kdaily** [chapmanb/bcbio-nextgen#1270] opened 2016-03-14 21:06 UTC
Looks like this error in conda is affecting bcbio-nextgen too:

https://github.com/conda/conda/issues/2232

Any suggestions to work around?

Error I'm getting:

```
    amazon-ebs: r-acepack-1.3_ 100% || Time: 0:00:00  20.00 MB/s
    amazon-ebs: Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-acepack-1.3_3.3-r3.2.2_1.tar.bz2 (ba387b95acee58fa81e355e728c922ca != 37c504b279cb00d6bd45f2b27a15f92e)
```

**Comment by kdaily** [comment] 2016-03-14 21:51
Hmmmm...maybe not (and just coincidence?) Other files are downloaded fine...

**Comment by chapmanb** [comment] 2016-03-15 01:14
Kenneth;
Sorry about the issues. I know there have been some conda MD5 problems but I've not been able to reproduce them yet to know a good workaround. I believe upgrading to the latest conda (4.0.4) will fix it. If you're on 4.0.3 it looks like you need to downgrade to the latest cached version on your system (using `bcbio_conda`) and then upgrade with (`bcbio_conda install conda`). This looks like the right approach to find an older version on your system to downgrade to:

https://github.com/conda/conda/issues/2232#issuecomment-195125055

Hopefully that gets you conda 4.0.4 and things work cleanly.

**Comment by kdaily** [comment] 2016-03-15 19:03
Thanks @chapmanb! OK, on doing that, I see that there is `conda-3.19-0` in the cache. Not sure how I can do this in an automated environment though (bcbio getting installed on an EC2 via a Packer build script)  - I would need to run the install once, check for failure, and then do this?

**Comment by kdaily** [comment] 2016-03-15 19:07
I downgraded (to 3.19-0) and then upgraded (to the latest), and now the md5 error happens on a different package:

```
Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-whisker-0.3_2-r3.2.2_1.tar.bz2 (54a78feaca1c5c7dfa7d78126d4d8d41 != 4604f56992cacbf5c5a027ded827b48a
```

**Comment by roryk** [comment] 2016-03-15 19:07
Yeah you're not alone, bumping to 4.0.4 breaks a bunch of the R packages for some reason.

**Comment by lpantano** [comment] 2016-03-15 19:08
yes, it happened to me as well. I checked with @roryk, seems 4.0.4 version is not totally right.

**Comment by chapmanb** [comment] 2016-03-16 00:39
Thanks all and sorry about the continued problems. It looks like something else is problematic with anaconda.org R packages right now. There are several different issues on the continuum conda repos but it looks like it's being worked on:

https://github.com/conda/conda-recipes/issues/637#issuecomment-197016327

Hopefully there'll be a fix in place soon. Thanks much for the patience.

**Comment by daler** [comment] 2016-03-16 01:08
The issue on conda/conda-recipes#637 seems to be fixed now -- at least I'm now able to install R packages through conda 4.0.4. Maybe give it a shot again?

**Comment by chapmanb** [comment] 2016-03-16 20:22
Thanks Ryan. @lpantano also reported it's working again. Kenneth, hopefully if you retry it'll work cleanly now. Thanks for the patience while this got sorted out.

**Closed by chapmanb** 2016-03-16 20:22 UTC

**Comment by kdaily** [comment] 2016-03-16 20:25
Success! Thanks!
