### ISSUE TITLE
bedtools groupby ops parameters is renamed op

### ISSUE THREAD

**Issue by WimS83** [chapmanb/bcbio-nextgen#1016] opened 2015-09-15 14:56 UTC
Hi Brad, 

The ops parameter for bedtools groupby seems to have changed from -ops to -op. 

At least this is my guess after running into this error when running bcbio bwa + freebayes on a small fastq on a single thread. I get the following error:

 bedtools groupby -prec 21 -ops first,first,max,first -i /data/Projects/bcbio/workdir10/tx/tmpE7B9gb/pybedtools.1HGu9Z.tmp -g 1,4 -c 1,2,3,4

Error message was:
***** ERROR: Unrecognized parameter: -ops *****
***** ERROR: Unrecognized parameter: first,first,max,first *****

**Comment by chapmanb** [comment] 2015-09-15 15:10
Sorry about the problem, we just pushed a fix for this:

https://github.com/chapmanb/bcbio-nextgen/commit/82b63147d1ebcced713e428868baa09c29f7ebbb

if you upgrade to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
This looks like an issue with the latest bedtools release (arq5x/bedtools2#300) but we can work around it by using the short parameter names. Hope this fixes it for you.

**Closed by chapmanb** 2015-09-15 15:10 UTC

**Comment by WimS83** [comment] 2015-09-15 15:19
Hi Brad. Thanks for you quick reply. Programming against a stable api (bedtools) is easier. 

upgrading to the development version results in this error:

DBG [shared.py]: Packages to install: cnvkit,hmmlearn,htseq,metasv,phylowgs,pyloh,pytabix,r,r-rgl,svtyper
[localhost] local: /data/Projects/bcbio/data/anaconda/bin/conda install -y -c https://conda.anaconda.org/bcbio -c https://conda.anaconda.org/r cnvkit hmmlearn htseq metasv phylowgs pyloh pytabix r r-rgl svtyper
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
..........
Error: No packages found in current linux-64 channels matching: r

**Comment by chapmanb** [comment] 2015-09-15 16:55
Sorry about the issue, I'm not sure why ssl certificates are failing here. I can't reproduce this but googling around it looks like you could hack it (conda/conda#1166) to skip ssl verification with:
```
/data/Projects/bcbio/data/anaconda/bin/conda config --set ssl_verify false
```
Hopefully that gets it installed for you.
