### ISSUE TITLE
ChiP-Seq pipeline: adapter trimming requires "trimmed" folder to be created during the run, but it is not

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1238] opened 2016-02-22 08:22 UTC
(cc @LMannarino)

As the subject says, adapter trimming (I'm mentioning the ChiP-Seq because I've done it, but might affect other runs). needs a `trimmed` directory to be created during the run in the work directory. However, at the moment this does not occur, and thus the pipeline fails (version 9.6.0; unfortunately I'm tied to stable releases due to a policy that has been requested to me).

**Comment by lpantano** [comment] 2016-02-22 15:11
Hi @lbeltrame and @LMannario,

sorry about the issue. I cannot reproduce this for that version. I got the trimmed folder in the run directory and the trimmed files. Maybe the logs/config files help to debug the issue you are having? Maybe it is some option related to the trimming step.

cheers

**Comment by lbeltrame** [comment] 2016-02-23 10:40
This is a part of the error shown:

```
 File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in trim_sample
    return sample.trim_sample(*args)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 57, in trim_sample
    out_files = trim_adapters(data)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/trim.py", line 29, in trim_adapters
    return _trim_adapters(to_trim, out_dir, name, config)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/trim.py", line 44, in _trim_adapters
    out_files = _cutadapt_trim(fastq_files, quality_format, to_trim, out_files, config)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/trim.py", line 60, in _cutadapt_trim
    do.run(cmd.format(**locals()), message)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/data/bcbio/anaconda/bin/cutadapt --times=2 --quality-base=33 --quality-cutoff=5 --format=fastq --adapter=AGATCGGAAGAG --adapter=CTCTTCCGATCT  --minimum-length=25  -o /mnt/data/projects/LPS190-2/LPS190-2_analysis/work/trimmed/CTRL.trimmed.fastq.gz /mnt/data/projects/LPS190-2/raw_data/CTRL_R1.fastq.gz
Traceback (most recent call last):
  File "/mnt/data/bcbio/anaconda/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 524, in main
    writer = open_writer(options.output, options.paired_output)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/cutadapt/seqio.py", line 679, in open
    return fastq_handler(file1)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/cutadapt/seqio.py", line 528, in __init__
    file = xopen(file, "w")
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/cutadapt/xopen.py", line 176, in xopen
    return buffered_writer(gzip.open(filename, mode))
  File "/mnt/data/bcbio/anaconda/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/mnt/data/projects/LPS190-2/LPS190-2_analysis/work/trimmed/CTRL.trimmed.fastq.gz'
```
And the reason is because `trimmed` doesn't exist. Trimming options are the same as the `illumina-chipseq` template provided by bcbio.

**Comment by lpantano** [comment] 2016-02-23 15:17
Hi @lbeltrame ,

I was looking at the code, and this folder is created by `transaction_file` function. I only see a problem if the temporary directory is set up somewhere else, then this folder doesn't get created in the work directory. I forced the creation of the folder there. 
The only other option I can think of is some kind of error just before the command runs with the file system avoiding to get this directory there. 

I don't know if this commit can get into the release like a patch if you want to use it (since you mention that only can use release version). I will mention to @chapmanb.

thanks and hope this fixes it

**Comment by chapmanb** [comment] 2016-02-23 15:40
Luca -- you can't test fixes on development versions? We don't do patches of releases, but could certainly roll a new release some point relatively soon. There are a couple of more things that need to go in and then we could do. In the short term, can you install a development version separate from your production version to ensure Lorena's fixes resolve your issue?

**Comment by lbeltrame** [comment] 2016-02-23 15:55
Unfortunately after issue #1067 hit us hard (but I no longer see that, luckily), I got requested to avoid upgrading unless needed (= stable versions only), and there are no real "development" machines (I handle them all myself on a best-effort basis). 

I'll see about upgrading one of the clusters and try again when I get around to it.

**Comment by chapmanb** [comment] 2016-02-23 16:01
Luca;
Understood. You don't need a separate development machine, but could install a development version of bcbio into a different directory, then put that in your PATH when testing. You'd have to symlink data directories to avoid downloading twice but otherwise that's the easiest way to test fixes but maintain a production install for your runs. Hope this helps.

**Comment by lpantano** [comment] 2016-04-08 20:01
It should be fixed in the last release, let me know if you have any other problem.

thanks a lot @lbeltrame

**Closed by lpantano** 2016-04-08 20:01 UTC
