### ISSUE TITLE
[Small RNAseq]  ValueError: Index contains duplicate entries, cannot reshape

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1425] opened 2016-06-10 00:31 UTC
Below is content of my configuration.
```
details:
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGGC
    aligner: star
    species: mmu
  analysis: smallRNA-seq
  description: PK 1
  files:
  - /BiO/BioProjects/ABC-Mouse-SmallRNA-2016-05-ABC/ABC/TN1604R0439.rm_first4bp.fastq.gz
  genome_build: mm10
  metadata:
    type: sample
```

Below is the error message.
```
[2016-06-10T00:22Z] multiprocessing: seqcluster_cluster
[2016-06-10T00:22Z] Create seqbuster count data at /BiO/BioProjects/ABC-Mouse-SmallRNA-2016-05-ABC/ABC-merged/work/mirbase.
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 323, in smallrnaseqpipeline
    samples = run_parallel("seqcluster_cluster", [samples])
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 88, in seqcluster_cluster
    return seqcluster.run_cluster(*args)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 81, in run_cluster
    out_mirna = _make_isomir_counts(data, out_dir=op.join(work_dir, "mirbase"))
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 193, in _make_isomir_counts
    out_files = _create_counts(out_dts, out_dir)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/seqcluster/seqbuster/__init__.py", line 419, in _create_counts
    ma, ma_mirna = _merge(out_dts)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/seqcluster/seqbuster/__init__.py", line 409, in _merge
    ma = df.pivot(index='isomir', columns='sample', values='counts')
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 3827, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/reshape.py", line 330, in pivot
    return indexed.unstack(columns)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/series.py", line 2061, in unstack
    return unstack(self, level, fill_value)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/reshape.py", line 405, in unstack
    fill_value=fill_value)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/reshape.py", line 99, in __init__
    self._make_selectors()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/reshape.py", line 137, in _make_selectors
    raise ValueError('Index contains duplicate entries, '
ValueError: Index contains duplicate entries, cannot reshape
```

Can you check this?

**Comment by lpantano** [comment] 2016-06-10 00:47
Hi

sorry about this. Any chance u can send me by email the files inside mirbase folder?
It seems at edge case and I would need to look it closer.

thanks

sent not from my computer

**Comment by hmkim** [comment] 2016-06-10 01:31
Ok, I will send the file by email for you.

I refer this and I solved it. (http://stackoverflow.com/questions/11232275/pandas-pivot-warning-about-repeated-entries-on-index)

Not yet, I can't sure it is no problem. Anyway I can pass the error. 

/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/seqcluster/seqbuster/__init__.py

```
408
409     #ma = df.pivot(index='isomir', columns='sample', values='counts')
410     ma = df.pivot_table(index='isomir', columns='sample', values='counts')
411     ma_mirna = ma
```

**Comment by lpantano** [comment] 2016-06-10 13:28
Hi @hmkim 

thanks for looking into this. I cannot reproduce the error. I used this script to tested (test.py):

```
from seqcluster.seqbuster import _create_counts, _read_miraligner, _tab_output
from bcbio import utils

fns = ["PI_1", "PI_2", "PK_1", "SI_1", "SK_1"]

out_dts = []
out_dir = "res"
utils.safe_makedir(out_dir)
for f in fns:
     miraligner_fn = "%s/%s.mirna" % (f, f)
     reads = _read_miraligner(miraligner_fn)
     out_file, dt, dt_pre = _tab_output(reads, miraligner_fn + ".back", f)
     out_dts.append(dt)

out_files = _create_counts(out_dts, out_dir)
```

I put this inside mirbase folder you sent me. and then just do `python test.py`. I updated to final version of pandas in case it was that, but I cannot get any error. The fix you propose can have further issue if you use isomiR package. 

If you can try to use this script and see if you get the same error. Probably you need to update seqcluster  using conda just to make sure we are all using the same version.

cheers

**Comment by lpantano** [comment] 2016-06-16 20:02
Hi @hmkim ,

Did you have time to test that? hopefully is not more an issue.

cheers

**Comment by lpantano** [comment] 2016-06-23 16:33
Hi,

closing this, let me know if happens again.

thanks for you time helping with the pipeline!

**Closed by lpantano** 2016-06-23 16:33 UTC

**Comment by mxhp75** [comment] 2019-07-25 04:57
For anyone who comes across this thread after encountering the same error.
I found the problem with my files to be an error in the sample ID column of the sample.csv file and subsequently a duplication in the relevant _description_ line of the full.yaml file. 
Hope that helps.

**Comment by lpantano** [comment] 2019-07-25 14:25
Thanks for posting this!
