### ISSUE TITLE
Stringtie only RNA-pipeline 

### ISSUE THREAD

**Issue by mmoisse** [chapmanb/bcbio-nextgen#2168] opened 2017-11-21 14:08 UTC
I tried to run a RNA-pipeline without relying on cufflinks using the folowing two line in the config file

      expression_caller: [stringtie, dexseq]
      transcript_assembler: stringtie

but doing so I ran into different problems:

1. gffcompare was not installed, apparently needed for stringie_merge, due to this the pipeline tried to use cufflink_merge but failed.
https://github.com/chapmanb/bcbio-nextgen/blob/6874f0154294bdd06c38da8a57e9e37baec0d4d8/bcbio/pipeline/rnaseq.py#L293
https://github.com/chapmanb/bcbio-nextgen/blob/6874f0154294bdd06c38da8a57e9e37baec0d4d8/bcbio/rnaseq/stringtie.py#L110-L117

I installed gffcompare which solved this issue

    bcbio_conda install -c bioconda gffcompare

2. The other issue was that the following code failed to find the `stringtie-assembly.gtf` files as the following code returned an empty list:
https://github.com/chapmanb/bcbio-nextgen/blob/6874f0154294bdd06c38da8a57e9e37baec0d4d8/bcbio/pipeline/rnaseq.py#L265-L266

To fix that I had to change the following two lines:
https://github.com/chapmanb/bcbio-nextgen/blob/6874f0154294bdd06c38da8a57e9e37baec0d4d8/bcbio/rnaseq/stringtie.py#L61
https://github.com/chapmanb/bcbio-nextgen/blob/6874f0154294bdd06c38da8a57e9e37baec0d4d8/bcbio/rnaseq/stringtie.py#L71

into:

    data = dd.set_assembled_gtf(data, assembly)

I was wondering if what I did is correct or that I should better use cuffLinks instead of Stringtie

Kind regards,
Matthieu

**Comment by roryk** [comment] 2017-11-22 20:07
Hi Matthieu,

Thanks for the great bug report. I added `gffcompare`to the installer so it should install that tool correctly. I can't reproduce the second issue, but I swapped the code around to not mutate the object in place which I hope will solve the problem. Let me know if it works for you.

**Comment by mmoisse** [comment] 2017-12-01 07:04
Hi Rory,

It seems to work for me.
Thanks

**Comment by mmoisse** [comment] 2017-12-05 10:53
I have a follow-up issue about the argument list being too long

````
[2017-12-03T11:37Z] Timing: transcript assembly
[2017-12-03T11:37Z] multiprocessing: run_stringtie_expression
[2017-12-03T11:37Z] multiprocessing: stringtie_merge
[2017-12-03T11:37Z] Merging transcriptome assemblies with Stringtie.
[2017-12-03T11:37Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 82, in _do_run
    env=env,
  File "/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
Traceback (most recent call last):
  File "/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 243, in rnaseqpipeline
    samples = rnaseq.assemble_transcripts(run_parallel, samples)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 299, in assemble_transcripts
    samples = run_parallel("stringtie_merge", [samples])
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 391, in stringtie_merge
    return rnaseq.stringtie_merge(*args)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 260, in stringtie_merge
    merged_gtf = stringtie.merge(to_merge, ref_file, gtf_file, num_cores, data)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/stringtie.py", line 108, in merge
    do.run(cmd.format(**locals()), message)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 82, in _do_run
    env=env,
  File "/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long


````

And indeed when I look at the command that was executed it is pretty long, with each of the 32 sample being present several times. I had to change the code back to what I wrote in my previous post to make it work again.

```
[2017-12-01T22:22Z] /share/bcbio/galaxy/../anaconda/bin/stringtie \
   --merge -o /results/RNA-merged/work/bcbiotx/tmpAylRwx/merged.gtf \
   -G /share/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf \
   (... over a 1000 files ...)
```

**Comment by roryk** [comment] 2017-12-05 14:56
Huh, this is unexpected.  Could you post a snippet of the extra files? Is it the same file over and over, or different files?

**Comment by mmoisse** [comment] 2017-12-05 15:19
A repetition of the same files

```
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1-rep/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition5-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition5-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c3/stringtie-assembly.gtf
```
```
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1-rep/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition5-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition5-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c3/stringtie-assembly.gtf
```
```
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1-rep/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition3-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition5-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition5-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition7-c3/stringtie-assembly.gtf
```
```
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c1-rep/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition1-c5/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c1-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c2-D2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c3/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition2-c4/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition6-c2/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c1/stringtie-assembly.gtf
/results/RNA-iPSC-merged/work/stringtie/Condition4-c2/stringtie-assembly.gtf
```

**Comment by roryk** [comment] 2017-12-06 14:47
Thanks @mmoisse. I added a fix for this, so if you update to the development version it shouldn't include these duplicated files in the merge command anymore. Thank you!

**Closed** 2017-12-06 14:47 UTC
