### ISSUE TITLE
bcbio_setup_genome.py: error while running prepare_tx_gff.py

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1609] opened 2016-10-26 15:50 UTC
Hi all,

I am trying to generate files for E. coli MG1655 to run the RNAseq pipeline. This might be related to Issue  #1608:

```
cd ~

FASTA=/ginkgo/bitome/users/lina/references/genomes/ecoli_mg1655.fa
ANNOTATION=/ginkgo/bitome/users/lina/references/genomes/ecoli_mg1655.gtf
NAME=ecoli_mg1655
BUILD=ecoli_mg1655_build

~/local/bin/bcbio_setup_genome.py -f $FASTA -g $ANNOTATION -i bowtie2 star seq bwa -n $NAME -b $BUILD &> ecoli_mg1655.log 
```

The log output with error messages is pasted here:

```
cat ecoli_mg1655.log

...


[2016-10-26 11:31:49] Beginning TopHat run (v2.0.10)
-----------------------------------------------
[2016-10-26 11:31:49] Checking for Bowtie
  Bowtie 2 not found, checking for older version..
          Bowtie version:    1.1.2.0
[2016-10-26 11:31:50] Checking for Samtools
        Samtools version:    0.1.19.0
[2016-10-26 11:31:50] Checking for Bowtie index files (genome)..
Error: Could not find Bowtie index files (/home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build.*.ebwt)
Creating gffutils database for /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf.
Writing out merged GTF file to /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf.
Creating gffutils database for /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/rRNA.gtf.
Traceback (most recent call last):
  File "/home/lina/cloudbiolinux/utils/prepare_tx_gff.py", line 821, in <module>
    main(args.org_build, args.gtf, args.fasta, genome_dir, args.cores)
  File "/home/lina/cloudbiolinux/utils/prepare_tx_gff.py", line 297, in main
    prepare_tophat_index(gtf_file, org_build, genome_fasta)
  File "/home/lina/cloudbiolinux/utils/prepare_tx_gff.py", line 504, in prepare_tophat_index
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tophat --transcriptome-index /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/tophat/ecoli_mg1655_build_transcriptome -G /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf -o /tmp/tmpWuzMSd /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build dummy.fq' returned non-zero exit status 1
Creating directories using /home/lina/local/share/bcbio/genomes as the base.
Genomes will be installed into /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build.
Installed genome as /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/seq/ecoli_mg1655_build.fa.
Installed GTF as /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/rnaseq/ref-transcripts.gtf.
Creating the bowtie2 index.
[localhost] local: mkdir /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/seq/../bowtie2
[localhost] local: ln -sf ../seq/ecoli_mg1655_build.fa /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build.fa
Creating the star index.
[localhost] local: mkdir /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/star
Creating the seq index.
[localhost] local: samtools faidx ecoli_mg1655_build.fa
[localhost] local: picard -Xms500m -Xmx3500m CreateSequenceDictionary REFERENCE=/home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/seq/ecoli_mg1655_build.fa OUTPUT=/home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/seq/ecoli_mg1655_build.dict
Creating the bwa index.
[localhost] local: mkdir bwa
[localhost] local: ln -sf /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/seq/ecoli_mg1655_build.fa
[localhost] local: bwa index -a bwtsw ecoli_mg1655_build.fa
[localhost] local: rm -f ecoli_mg1655_build.fa
Traceback (most recent call last):
  File "/home/lina/local/bin/bcbio_setup_genome.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_setup_genome.py')
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 277, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/lina/local/share/bcbio/anaconda/bin/python /home/lina/cloudbiolinux/utils/prepare_tx_gff.py --cores 1 --genome-dir /home/lina/local/share/bcbio/genomes --gtf /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/rnaseq/ref-transcripts.gtf ecoli_mg1655 ecoli_mg1655_build' returned non-zero exit status 1
```

First, I actually have bowtie2 installed:

```
lina@compute1:~$ which bowtie2
/usr/bin/bowtie2

lina@compute1:~$ bowtie2 --version
/usr/bin/bowtie2-align-s version 2.2.4
64-bit
Built on sputnik
Sun Oct 26 07:21:16 UTC 2014
Compiler: gcc version 4.9.1 (Debian 4.9.1-19) 
Options: -O3 -m64 -msse2  -funroll-loops -g3 -Wl,-z,relro
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

But later in the log file, it says `Creating the bowtie2 index.` I assume this might be a hard-coded message (?).

It looks like the `prepare_tx_gff.py` script contains a lot of hard-coded builds for non-microbial organisms. Is it appropriate for organisms that are not in the UCSC browser?

Thanks for any advice!
~Lina

**Comment by lpantano** [comment] 2016-10-26 18:05
Hi,

sorry about this.

sometimes automatizing the indexing of these genomes bring some problems.

Can you go to this folder: /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/

what do you have there and are they empty?

right now I am not sure why tophat2 and bowtie2 are failing. Are tophat2 and bowite2 installed in the same place? not sure if this is even important.

**Comment by lfaller** [comment] 2016-10-26 18:53
No worries, thanks for offering to help!

```
$ ls -la /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/
total 10984
drwxr-xr-x 3 lina go    4096 Oct 26 11:31 .
drwxr-xr-x 8 lina go    4096 Oct 26 11:31 ..
-rw-r--r-- 1 lina go     172 Oct 26 11:31 dummy.fq
-rw-r--r-- 1 lina go  150599 Oct 26 11:31 ref-transcripts.bed
-rw-r--r-- 1 lina go 1078212 Oct 26 11:31 ref-transcripts.dexseq.gff3
-rw-r--r-- 1 lina go  407398 Oct 26 11:31 ref-transcripts.genePred
-rw-r--r-- 1 lina go 2649186 Oct 26 11:31 ref-transcripts.gtf
-rw-r--r-- 1 lina go 6062080 Oct 26 11:31 ref-transcripts.gtf.db
-rw-r--r-- 1 lina go   51348 Oct 26 11:31 ref-transcripts-mask.gtf
-rw-r--r-- 1 lina go  438877 Oct 26 11:31 ref-transcripts.refFlat
-rw-r--r-- 1 lina go   51348 Oct 26 11:31 rRNA.gtf
-rw-r--r-- 1 lina go  200704 Oct 26 11:31 rRNA.gtf.db
-rw-r--r-- 1 lina go   11355 Oct 26 11:31 rRNA.interval_list
drwxr-xr-x 2 lina go    4096 Oct 26 11:31 tophat
-rw-r--r-- 1 lina go   58461 Oct 26 11:31 tx2gene.csv
-rw-r--r-- 1 lina go     109 Oct 26 11:31 version.txt
```

Also, it looks like both bowtie2 and tophat2 are in the same location:

```
$ which tophat2
/home/lina/local/bin/tophat2
$ which bowtie2
/home/lina/local/bin/bowtie2
```

**Comment by lpantano** [comment] 2016-10-27 15:38
thanks.

according to the log error this is the command that fails:
tophat --transcriptome-index /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/tophat/ecoli_mg1655_build_transcriptome -G /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf -o /tmp/tmpWuzMSd /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build dummy.fq

it seems is assuming this folder exists: /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build

Can you see if that folder is there? 

I am reading this better, and it says is not finding bowtie2 indexes, not bowtie2 right?. But the bowtie2 is created after that.
Anyway, did you tried to re-start, just using the same bcbio command and see if you get exactly the same?

let me know if you have the bowtie2 index folder, and if re-starting gives a different error?

**Comment by lfaller** [comment] 2016-10-27 15:50
Hi Lorena,

I checked, and I don't have this folder:

```
$ pwd
/home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2

$ ls -lah
total 15M
drwxr-xr-x 2 lina ginkgo 4.0K Oct 26 11:31 .
drwxr-xr-x 8 lina ginkgo 4.0K Oct 26 11:31 ..
-rw-r--r-- 1 lina ginkgo 5.5M Oct 26 11:31 ecoli_mg1655_build.1.bt2
-rw-r--r-- 1 lina ginkgo 1.2M Oct 26 11:31 ecoli_mg1655_build.2.bt2
-rw-r--r-- 1 lina ginkgo   17 Oct 26 11:31 ecoli_mg1655_build.3.bt2
-rw-r--r-- 1 lina ginkgo 1.2M Oct 26 11:31 ecoli_mg1655_build.4.bt2
lrwxrwxrwx 1 lina ginkgo   28 Oct 26 11:31 ecoli_mg1655_build.fa -> ../seq/ecoli_mg1655_build.fa
-rw-r--r-- 1 lina ginkgo 5.5M Oct 26 11:31 ecoli_mg1655_build.rev.1.bt2
-rw-r--r-- 1 lina ginkgo 1.2M Oct 26 11:31 ecoli_mg1655_build.rev.2.bt2
```

I can create it, if that helps. Is it supposed to contain the bowtie2 indexes?


I ran the same command two more times, but I still get the same error message as before:

```
[2016-10-27 11:47:21] Beginning TopHat run (v2.0.10)
-----------------------------------------------
[2016-10-27 11:47:21] Checking for Bowtie
  Bowtie 2 not found, checking for older version..
		  Bowtie version:	 1.1.2.0
[2016-10-27 11:47:21] Checking for Samtools
		Samtools version:	 0.1.19.0
[2016-10-27 11:47:21] Checking for Bowtie index files (genome)..
Error: Could not find Bowtie index files (/home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build.*.ebwt)
Writing out merged GTF file to /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf.
Traceback (most recent call last):
  File "/home/lina/cloudbiolinux/utils/prepare_tx_gff.py", line 821, in <module>
    main(args.org_build, args.gtf, args.fasta, genome_dir, args.cores)
  File "/home/lina/cloudbiolinux/utils/prepare_tx_gff.py", line 297, in main
    prepare_tophat_index(gtf_file, org_build, genome_fasta)
  File "/home/lina/cloudbiolinux/utils/prepare_tx_gff.py", line 504, in prepare_tophat_index
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tophat --transcriptome-index /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/tophat/ecoli_mg1655_build_transcriptome -G /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf -o /tmp/tmp1p_L6I /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build dummy.fq' returned non-zero exit status 1
Creating directories using /home/lina/local/share/bcbio/genomes as the base.
Genomes will be installed into /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build.
Installed genome as /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/seq/ecoli_mg1655_build.fa.
Installed GTF as /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/rnaseq/ref-transcripts.gtf.
Creating the bowtie2 index.
Creating the star index.
Creating the seq index.
Creating the bwa index.
Traceback (most recent call last):
  File "/home/lina/local/bin/bcbio_setup_genome.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_setup_genome.py')
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 277, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/home/lina/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/lina/local/share/bcbio/anaconda/bin/python /home/lina/cloudbiolinux/utils/prepare_tx_gff.py --cores 1 --genome-dir /home/lina/local/share/bcbio/genomes --gtf /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/rnaseq/ref-transcripts.gtf ecoli_mg1655 ecoli_mg1655_build' returned non-zero exit status 1
```


I also tried running the offending command on its own:

```
$ tophat --transcriptome-index /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/tophat/ecoli_mg1655_build_transcriptome -G /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/tmpcbl/ref-transcripts.gtf -o /tmp/tmp1p_L6I /home/lina/local/share/bcbio/genomes/ecoli_mg1655/ecoli_mg1655_build/bowtie2/ecoli_mg1655_build dummy.fq

[2016-10-27 11:48:06] Beginning TopHat run (v2.0.10)
-----------------------------------------------
[2016-10-27 11:48:06] Checking for Bowtie
  Bowtie 2 not found, checking for older version..
Error: Bowtie not found on this system.

$ which bowtie
$ which bowtie2
/usr/bin/bowtie2
```

If possible, I assume I should be using bowtie2. Is there a reason why it wouldn't find bowtie2 even though it's in my path?

Thanks for your help!

**Comment by lpantano** [comment] 2016-10-28 16:08
ok, I will try to replicate this.

Any way you can send me the FASTA and GTF file to me?

thanks!

**Comment by lfaller** [comment] 2016-10-28 18:37
I will -- thanks for helping look into this!

Link to dropbox: https://www.dropbox.com/sh/dw88466sp055r6d/AACs75EbsmxAq0-mUDxKwQcIa?dl=0

Let me know if that works :)

**Comment by lpantano** [comment] 2016-11-03 23:08
Hi,

I  cannot replicate this, so I am guessing the problem is missing bowtie2 for some reason, even if it is there.  

Are tophat2 or bowti2 binary the ones installed by bcbio? if yes, I have not many more ideas for now. But will try to go further tomorrow.

sorry, my week was epic and couldn't do this early.

**Comment by lfaller** [comment] 2016-11-04 14:38
No worries and thanks for looking into this for me! 

I noticed that there is another version of bowtie2 installed. The one that's on my PATH is v 2.2.4 and the other one is 2.2.8 and I think that one was installed by bcbio. I will try to figure out if the newer one works. Otherwise I'll start fresh.

**Comment by lpantano** [comment] 2017-05-06 21:51
Hi @lfaller 

I will close this guessing it worked at the end. Let us know if you find more issues. I hope it worked at the end.

**Closed by lpantano** 2017-05-06 21:51 UTC
