### ISSUE TITLE
Error in downloading snpEff_v4_3_GRCh38.86.zip file (bcbio_nextgen.py upgrade)

### ISSUE THREAD

**Issue by asad** [chapmanb/bcbio-nextgen#1736] opened 2017-01-10 14:44 UTC
Hi,

The <i>bcbio_nextgen.py upgrade</i> script is unable to <i>wget snpEff_v4_3_GRCh38.86.zip</i> file (although 'wget' link works on the command line but fails in the script).

```
bin/bcbio_nextgen.py upgrade -u development --tooldir=BCBIO-NEXTGEN --genomes hg38-noalt --genomes hg38
```
Any pointer would be very helpful.
Thank you!
Best,
Asad

Error log:

```
Installing snpEff database GRCh38.86 in BCBIO-NEXTGEN/share/genomes/Hsapiens/hg38-noalt/snpeff
--2017-01-10 14:35:50--  http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
....
......
20 redirections exceeded.
Traceback (most recent call last):
  File "bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 292, in upgrade_bcbio_data
    _upgrade_snpeff_data(s["fabricrc_overrides"]["galaxy_home"], args, remotes)
  File "BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 357, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "-c", "-O", dl_file, dl_url])
  File "BCBIO-NEXTGEN/share/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '-c', '-O', 'snpEff_v4_3_GRCh38.86.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip']' returned non-zero exit status 8
```

**Comment by chapmanb** [comment] 2017-01-10 16:40
Asad;
Sorry about the issues. I'm not able to reproduce this now and downloads seem to proceed cleanly. It's possible this was a temporary issue with sourceforge downloads. Could you retry the upgrade you're running? It should pick up where it left off and hopefully work this time.

**Comment by lpantano** [comment] 2017-03-14 20:29
Hi @asad 

I am closing this because it seems is not a problem anymore, please feel free to open an issue if you find again the problem.

thanks!

**Closed by lpantano** 2017-03-14 20:29 UTC

**Comment by davidballi** [comment] 2017-03-16 16:09
Hi @chapmanb @asad @lpantano,

I'm having the same issue as well.  Any thoughts?  
```
sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir /usr/local --genomes hg38 --aligners bwa --isolate -u stable

Installing snpEff database GRCh38.86 in /usr/local/share/bcbio/genomes/Hsapiens/hg38/snpeff
--2017-03-16 16:05:26--  http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cytranet.dl.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip [following]
--2017-03-16 16:05:26--  https://cytranet.dl.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip
Resolving cytranet.dl.sourceforge.net (cytranet.dl.sourceforge.net)... 74.82.59.181
Connecting to cytranet.dl.sourceforge.net (cytranet.dl.sourceforge.net)|74.82.59.181|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
....
20 redirections exceeded.
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.2', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.2-py2.7.egg-info/scripts/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
    _upgrade_snpeff_data(s["fabricrc_overrides"]["galaxy_home"], args, remotes)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 358, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "-c", "-O", dl_file, dl_url])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '-c', '-O', 'snpEff_v4_3_GRCh38.86.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip']' returned non-zero exit status 8
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 246, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir', '/usr/local', '--genomes', 'hg38', '--aligners', 'bwa', '--isolate', '-u', 'stable', '--data']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment] 2017-03-16 17:31
David -- I still haven't been able to reproduce this and think it's due to sourceforge instability. If you re-try the install/upgrade command, does it fail consistently? Hopefully re-starting it will work for you.

**Comment by DennisSchwartz** [comment] 2017-05-31 10:38
I have the same problem intermittently. It looks like Sourceforge is sending 302s and then it exceeds the 20 redirects limit.

**Comment by chapmanb** [comment] 2017-05-31 15:34
Dennis -- thanks for the report. Unfortunately this is due to Sourceforge instability so we don't have a good way to work around it. I wish I had better option than waiting and trying a restart, but hope that hacky solution will work for you.
