### ISSUE TITLE
bug in “python bcbio_prepare_samples.py ?

### ISSUE THREAD

**Issue by AurelieMLB** [chapmanb/bcbio-nextgen#873] opened 2015-06-01 13:14 UTC
Hello,

I have access to bcbio-nextgen version 0.8.7.
I am trying to use “python bcbio_prepare_samples.py” but it is complaining about the function is_fastq( ) line 51 having 2 arguments.
I tried to copy the program locally to be able to make prints. It seems that if I remove the second “True” argument, the program pass this step. But then it cannot find the module “prepare_bcbio_samples”.
Would it be possible that this is a small bug please? Or I am doing something wrong? If it is a bug how can I fix it please? (given that I do not have the rights to edit the python file).

Many thanks

**Comment by lpantano** [comment] 2015-06-01 13:53
hi,

sorry about that issues. it seems there is the script needs a newer version of bcbio. Now the script is part of the main bcbio tools, so you should be able to call it directly doing bcbio_prepare_samples.py.

any way bcbio can be updated in your system?

sent not from my computer

**Comment by mjafin** [comment] 2015-06-01 13:55
@AurelieMLB @lpantano, just chiming in, we have 0.8.9 installed on the cluster. Aurelie can you use 0.8.9 instead?

**Comment by AurelieMLB** [comment] 2015-06-01 14:29
OK. Thank you I will try this.

**Comment by AurelieMLB** [comment] 2015-06-01 15:45
Hello

It seemed promising at first but then I had:
>bcbio_prepare_samples.py --out merged_fastq_file --csv Myproject_prepSamples.csv
Traceback (most recent call last):
  File "/apps/bcbio-nextgen/0.8.9/rhel6-x64/anaconda/bin/bcbio_prepare_samples.py", line 116, in <module>
    log.setup_local_logging(config, parallel)
  File "/apps/bcbio-nextgen/0.8.9/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/log/__init__.py", line 139, in setup_local_logging
    handler = _create_log_handler(config, direct_hostname=wrapper is not None)
  File "/apps/bcbio-nextgen/0.8.9/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/log/__init__.py", line 65, in _create_log_handler
    utils.safe_makedir(log_dir)
  File "/apps/bcbio-nextgen/0.8.9/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 155, in safe_makedir
    os.makedirs(dname)
  File "/apps/bcbio-nextgen/0.8.9/rhel6-x64/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/apps/bcbio-nextgen/0.8.9/rhel6-x64/share/java/log'

Does it make any sense to anyone please?

Apologies if it is me doing something stupid.

Many thanks

**Comment by lpantano** [comment] 2015-06-01 16:42
Hi,
sorry about that, it is weird because it's like trying to create the log inside that `/apps/bcbio-nextgen/0.8.9/rhel6-x64/share/java/log` instead of inside the working directory. 
I will try to reproduce the error and come back.

**Comment by lpantano** [comment] 2015-06-01 17:05
Hi, to avoid updating the main `bcbio`, could you download the script again https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_prepare_samples.py, and use the `bcbio` python to run it: `/apps/bcbio-nextgen/0.8.9/rhel6-x64/anaconda/bin/python bcbio_prepare_samples.py --out merged_fastq_file --csv Myproject_prepSamples.csv` and see what happens? 

sorry about the issue, and thanks to help with the problem.

**Comment by AurelieMLB** [comment] 2015-06-01 20:52
Hello,
Your solution did work very well.
Thank you so much !

**Comment by lpantano** [comment] 2015-06-01 21:08
Thank you so much!

**Closed by lpantano** 2015-06-01 21:08 UTC
