### ISSUE TITLE
Running cancer-syn3-chr6.yaml throws error

### ISSUE THREAD

**Issue by asad** [chapmanb/bcbio-nextgen#1723] opened 2017-01-04 16:09 UTC
Hi,

I am new to this tool. 

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/teaching/cancer-syn3-chr6.yaml

The above mentioned pipeline (config/cancer-syn3-chr6.yaml)  gives me the following error. 
I was under the impression that gatk is not required for this particular run.

May be I am wrong, any pointers?

Kind regards

[2017-01-04T15:42Z] GATK: VariantAnnotator
[2017-01-04T15:42Z] GATK jar file not found. Have you run "gatk-register"?
[2017-01-04T15:42Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/bin:$PATH && /mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/bin/gatk -Xms454M -Xmx9G -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/bcbiotx/tmpmzSIBV -T VariantAnnotator -R /mnt/biousb2/BCBIO-NEXTGEN/share/genomes/Hsapiens/hg38/seq/hg38.fa --variant /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/freebayes/chr6/syn3-chr6_0_16129694.vcf.gz --out /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/bcbiotx/tmpy5Irea/syn3-chr6_0_16129694-gatkann.vcf.gz -L /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/freebayes/chr6/syn3-chr6_0_16129694.vcf.gz --dbsnp /mnt/biousb2/BCBIO-NEXTGEN/share/genomes/Hsapiens/hg38/variation/dbsnp-147.vcf.gz -I /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/align/syn3-normal/syn3-normal-sort.bam -I /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/align/syn3-tumor/syn3-tumor-sort.bam -A BaseQualityRankSumTest -A FisherStrand -A GCContent -A HaplotypeScore -A HomopolymerRun -A MappingQualityRankSumTest -A MappingQualityZero -A QualByDepth -A ReadPosRankSumTest -A RMSMappingQuality --allow_potentially_misencoded_quality_scores -U ALL --read_filter BadCigar --read_filter NotPrimaryAlignment
GATK jar file not found. Have you run "gatk-register"?
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/LOCAL_NGS_TOOLS/tools/BCBIO-NEXTGEN/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/LOCAL_NGS_TOOLS/tools/BCBIO-NEXTGEN/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 150, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 181, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 216, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 316, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 95, in run_freebayes
    assoc_files, region, out_file)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 203, in _run_freebayes_paired
    config)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/variation/annotation.py", line 162, in annotate_nongatk_vcf
    broad_runner.run_gatk(params)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 311, in run_gatk
    log_error=log_error)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/bin:$PATH && /mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/bin/gatk -Xms454M -Xmx9G -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/bcbiotx/tmpmzSIBV -T VariantAnnotator -R /mnt/biousb2/BCBIO-NEXTGEN/share/genomes/Hsapiens/hg38/seq/hg38.fa --variant /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/freebayes/chr6/syn3-chr6_0_16129694.vcf.gz --out /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/bcbiotx/tmpy5Irea/syn3-chr6_0_16129694-gatkann.vcf.gz -L /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/freebayes/chr6/syn3-chr6_0_16129694.vcf.gz --dbsnp /mnt/biousb2/BCBIO-NEXTGEN/share/genomes/Hsapiens/hg38/variation/dbsnp-147.vcf.gz -I /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/align/syn3-normal/syn3-normal-sort.bam -I /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/align/syn3-tumor/syn3-tumor-sort.bam -A BaseQualityRankSumTest -A FisherStrand -A GCContent -A HaplotypeScore -A HomopolymerRun -A MappingQualityRankSumTest -A MappingQualityZero -A QualByDepth -A ReadPosRankSumTest -A RMSMappingQuality --allow_potentially_misencoded_quality_scores -U ALL --read_filter BadCigar --read_filter NotPrimaryAlignment
GATK jar file not found. Have you run "gatk-register"?
' returned non-zero exit status 1

**Comment by chapmanb** [comment] 2017-01-04 19:26
Syed;
Thanks for the report and sorry about the issue. You're right that bcbio doesn't need GATK for this workflow and should be skipping this annotation step if not present. I've been trying to reproduce the issue using the latest development version without GATK installed but can not seem to do so.

Which version of bcbio are you running? If it's an older version I know we fixed some issues around this and you could try updating with:
```
bcbio_nextgen.py upgrade - u development
```
to see if that fixes the issue. If not, any information about how you installed bcbio would be helpful to trying to understand the source of the issue so we can fix. Thanks for the help debubbing.

**Comment by asad** [comment] 2017-01-04 20:32
Thanks @chapmanb;

### AFAIK - I have followed the following steps:

1.  I have installed the tool using the following command
    ```
     wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
    ```

    ```
    bcbio_nextgen_install.py path/to/share --tooldir=path/to/tool/dir --genomes hg38 --distribution ubuntu
    ```
2.  Configured the genomes and indexed it using the following command
    
    ```
     bin/bcbio_setup_genome.py -f /path/to/share/genomes/Hsapiens/hg38/seq/hg38.fa -n Hsapiens -b hg38 -i bowtie bowtie2 bwa novoalign rtg snap star ucsc seq --cores 8
     ```

3. Installed External Data
    
     ```
      bin/bcbio_nextgen.py upgrade -u skip --tooldir=path/to/tool/dir --genomes hg38 --data --datatarget vep --datatarget variation
      ```
4. Then upgraded it to the development version <b>1.0.1a0</b>

     ```
     bin/bcbio_nextgen.py upgrade -u development --tooldir=path/to/tool/dir
     ```

5. Preparing and Running

     ```
     mkdir -p run
     cd run
     wget https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/teaching/cancer-syn3-chr6-prep.sh
     bash cancer-syn3-chr6-prep.sh
     ```

6. Running test case

    ```
     cd cancer-syn3-chr6/work
     path/to/bin/bcbio_nextgen.py ../config/cancer-syn3-chr6.yaml -n 16
     
     ```

**Comment by chapmanb** [comment] 2017-01-04 21:26
Thanks for all the details. This looks like the generally right procedure do I don't see any issues there. Apologies, I'm not sure why the check for gatk is indicating it is present and continuing, but I pushed a fix to attempt to resolve it. Could you try updating to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
and re-running? Fingers crossed it will now do the right thing.

This isn't anything to do with your problem, but there is no need to do step 2 in your process as a separate step. `bcbio_setup_genome.py` is meant for other genomes bcbio doesn't support by default. You can install other indices for hg38 with the `--aligners` argument:
```
bcbion_nextgen.py upgrade --data --genomes hg38 --aligners bowtie --aligners bowtie2 --aligners bwa --aligners novoalign --aligners rtg --aligners snap --aligners star
```
Hope this helps.

**Comment by asad** [comment] 2017-01-04 22:26
Thank you for the patch and tips, much appreciated!
It ran but unfortunately it didn't finish the job.  It crashed with the following error in the end, any pointers please?

[2017-01-04T22:19Z] Prioritize: convert to tab delimited
[2017-01-04T22:19Z] 
[2017-01-04T22:19Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/structural/syn3-tumor/prioritize/syn3-tumor-lumpy-prioritize-wgts-prep-simple-prep.vcf.gz | vawk -v SNAME=syn3-tumor -v CALLER=lumpy '{if (($7 == "PASS" || $7 == ".") && (S$syn3-tumor$GT != "0/0")) print CALLER,SNAME,$1,$2,I$END,I$SVTYPE=="BND" ? I$SVTYPE":"$3":"I$MATEID : I$SVTYPE,I$LOF,I$SIMPLE_ANN,S$syn3-tumor$SR,S$syn3-tumor$PE,S$syn3-tumor$PR}' > /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/bcbiotx/tmpjbldwi/syn3-tumor-lumpy-prioritize.tsv

gzip: stdout: Broken pipe
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/arahman/LOCAL_NGS_TOOLS/tools/BCBIO-NEXTGEN/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/arahman/LOCAL_NGS_TOOLS/tools/BCBIO-NEXTGEN/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 180, in variant2pipeline
    samples = structural.run(samples, run_parallel, "ensemble")
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 146, in run
    for xs in to_process.values()))
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 244, in detect_sv
    return structural.detect_sv(*args)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 165, in detect_sv
    for svdata in caller_fn(items):
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/structural/prioritize.py", line 38, in run
    for vcaller, vfile, post_prior_fn in inputs]
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/structural/prioritize.py", line 122, in _prioritize_vcf
    do.run(cmd.format(**locals()), "Prioritize: convert to tab delimited")
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; zcat /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/structural/syn3-tumor/prioritize/syn3-tumor-lumpy-prioritize-wgts-prep-simple-prep.vcf.gz | vawk -v SNAME=syn3-tumor -v CALLER=lumpy '{if (($7 == "PASS" || $7 == ".") && (S$syn3-tumor$GT != "0/0")) print CALLER,SNAME,$1,$2,I$END,I$SVTYPE=="BND" ? I$SVTYPE":"$3":"I$MATEID : I$SVTYPE,I$LOF,I$SIMPLE_ANN,S$syn3-tumor$SR,S$syn3-tumor$PE,S$syn3-tumor$PR}' > /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/bcbiotx/tmpjbldwi/syn3-tumor-lumpy-prioritize.tsv

gzip: stdout: Broken pipe
' returned non-zero exit status 1

**Comment by asad** [comment] 2017-01-04 23:47
Also, found an error in log file.

```
[2017-01-04T22:10Z] lumpyexpress : syn3-normal
[2017-01-04T22:10Z] Sourcing executables from /mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/bin/lumpyexpress.config ...
[2017-01-04T22:10Z] 
[2017-01-04T22:10Z] Checking for required python modules (/mnt/biousb2/BCBIO-NEXTGEN/share/anaconda/bin/python)...
[2017-01-04T22:10Z] 
[2017-01-04T22:10Z]     create temporary directory
[2017-01-04T22:10Z] Calculating insert distributions...
[2017-01-04T22:10Z] sambamba-view:  (Broken pipe)
```

**Comment by chapmanb** [comment] 2017-01-05 03:00
Syed;
Glad that fixed the previous error. It looks like we're running into something new during structural variant prioritization. Could you try running the failing command outside of bcbio:
```
zcat /mnt/biousb2/NGS_DATA/cancer/cancer-syn3-chr6/work/structural/syn3-tumor/prioritize/syn3-tumor-lumpy-prioritize-wgts-prep-simple-prep.vcf.gz | vawk -v SNAME=syn3-tumor -v CALLER=lumpy '{if (($7 == "PASS" || $7 == ".") && (S$syn3-tumor$GT != "0/0")) print CALLER,SNAME,$1,$2,I$END,I$SVTYPE=="BND" ? I$SVTYPE":"$3":"I$MATEID : I$SVTYPE,I$LOF,I$SIMPLE_ANN,S$syn3-tumor$SR,S$syn3-tumor$PE,S$syn3-tumor$PR}' > syn3-tumor-lumpy-prioritize.tsv
```
Does it work, or fail consistently? Are there any useful error messages. It seems like something is slightly problematic with your setup but I'm not sure what. What type of system are you running this on and I'll see if I can reproduce.

The sambamba-view message you found is not a problem, that's an expected message. It reads the start of a BAM file, so the shell reports the pipe is broken when it doesn't read the full file.

Hope that helps.

**Comment by asad** [comment] 2017-01-05 09:29
Hi Brad;

Here is the output from the above mentioned command.

```
tail syn3-tumor-lumpy-prioritize.tsv 
awk: line 1: illegal reference to array fmt
awk: line 1: illegal reference to array fmt
awk: line 1: illegal reference to array fmt
awk: line 1: illegal reference to array fmt
awk: line 1: illegal reference to array x
```
Thanks,

**Comment by chapmanb** [comment] 2017-01-05 18:58
Syed;
Thanks for testing and for the file. This works cleanly on my system so from the error messages it looks like an incompatibility with the vawk command and your version of awk. What does:
```
awk --version
```
say? What type of system are you running bcbio on? I'll work on getting a fix in place for these, which will need an update of vawk to use an internally installed gawk (instead of your default system awk). I should have that settled early tomorrow and can report back here. In the short term you can disable prioritization by commenting out `svprioritize: cancer/civic` in your config. Hopefully this will help your test run get to completion. Thanks again for all the help debugging this.

**Comment by asad** [comment] 2017-01-05 21:16
@chapmanb 👍 

I had to install `gawk` instead of `vawk`.

```
awk --version
GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
```

Good news is that it works smoothy and yes creates far less noisy debugging logging info.
Thanks a lot for your help. 

I am already liking the tool!

**Closed** 2017-01-06 09:08 UTC

**Comment by chapmanb** [comment] 2017-01-06 11:36
Syed;
Thanks for confirming that it was a gawk/awk issue and glad it now finishes correctly. I pushed a permanent fix so vawk will use an internally installed gawk and should no longer rely on the external installation. Hope things continue to run cleanly for you on real analyses.
