### ISSUE TITLE
bcbio_nextgen for gemini install

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#730] opened 2015-01-22 07:49 UTC
Hi Brad,

When I install the gemini use:

bcbio_nextgen.py upgrade --tools --toolplus data

got the following error:

Requirement already satisfied (use --upgrade to upgrade): Unidecode>=0.04.14 in /data1/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): gemini==0.11.0 in /data1/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): pydot in /data1/bcbio/anaconda/lib/python2.7/site-packages/pydot-1.0.28-py2.7.egg (from python-graph-dot>=1.8.2->-r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=2.1.11 in /data1/bcbio/anaconda/lib/python2.7/site-packages (from ipython-cluster-helper>=0.2.23->-r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): ipython>=1.1.0 in /data1/bcbio/anaconda/lib/python2.7/site-packages (from ipython-cluster-helper>=0.2.23->-r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): netifaces>=0.10.3 in /data1/bcbio/anaconda/lib/python2.7/site-packages (from ipython-cluster-helper>=0.2.23->-r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /data1/bcbio/anaconda/lib/python2.7/site-packages/setuptools-12.0.4-py2.7.egg (from pydot->python-graph-dot>=1.8.2->-r https://raw.githubusercontent.com/arq5x/gemini/master/requirements.txt (line 9))
Traceback (most recent call last):
  File "gemini_install.py", line 325, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 61, in main
    gemini = install_gemini(anaconda, remotes, args.datadir, args.tooldir, args.sudo)
  File "gemini_install.py", line 107, in install_gemini
    _add_missing_inits(python_bin)
  File "gemini_install.py", line 170, in _add_missing_inits
    with open(pygraph_init, "w") as out_handle:
IOError: [Errno 20] Not a directory: '/data1/bcbio/anaconda/lib/python2.7/site-packages/python_graph_core-1.8.2-py2.7.egg/pygraph/__init__.py'
Traceback (most recent call last):
  File "bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/data1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 75, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/data1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 345, in upgrade_thirdparty_tools
    _install_toolplus(args, manifest_dir)
  File "/data1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 355, in _install_toolplus
    _install_gemini(args.tooldir, _get_data_dir(), args)
  File "/data1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 437, in _install_gemini
    subprocess.check_call(cmd)
  File "/data1/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data1/bcbio/anaconda/bin/python', '-E', 'gemini_install.py', '/data1/bcbio_tools', '/data1/bcbio', '--notools', '--nodata', '--sharedpy', '--nosudo']' returned non-zero exit status 1

It was about the package python_graph_core, could you please check it ?

Thanks so much!

**Comment by chapmanb** [comment] 2015-01-22 09:33
There was an issue with `python-graph-core` a while back but I'm not sure what exactly happened with your installion here. If first upgrading to the latest release (#729) doesn't fix it, you can manually remove that dependency and let it get re-installed:
```
rm -rf /data1/bcbio/anaconda/lib/python2.7/site-packages/python_graph_core-1.8.2-py2.7.egg/
bcbio_nextgen.py upgrade --tools --toolplus data
```
Hope this fixes it for you.

**Comment by chapmanb** [comment] 2015-03-11 08:41
Did the manual removal and re-update help resolve this issue? Are you still stuck here?

**Comment by junchend** [comment] 2015-03-12 02:55
Yes, I still can't go through, python-graph-core can't install directly.

**Comment by chapmanb** [comment] 2015-03-12 09:01
Sorry about the continued problems. We'll probably need additional information to help resolve this. An idea is to manually remove and re-install python-graph-core:
```
rm -rf /data1/bcbio/anaconda/lib/python2.7/site-packages/python_graph_core*
/data1/bcbio/anaconda/bin/pip uninstall python-graph-core
/data1/bcbio/anaconda/bin/pip install python-graph-core
```
If you re-start the installation does this help? If not, what error message do you get? What does the python-graph-core directory look like:
```
ls -lh /data1/bcbio/anaconda/lib/python2.7/site-packages/python_graph_core-1.8.2-py2.7.egg/pygraph/
```
Hope this helps.

**Comment by junchend** [comment] 2015-03-12 09:26
I installed it manually by:

/data1/bcbio/anaconda/bin/easy_install python-graph-core-1.8.2.tar.gz
/data1/bcbio/anaconda/lib/python2.7/site-packages/setuptools-14.0-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'HTS.
/data1/bcbio/anaconda/lib/python2.7/site-packages/setuptools-14.0-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'arv.
Processing python-graph-core-1.8.2.tar.gz
Writing /tmp/easy_install-zoZZfZ/python-graph-core-1.8.2/setup.cfg
Running python-graph-core-1.8.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zoZZfZ/python-graph-core-1.8.2/egg-dist-tmp-b
zip_safe flag not set; analyzing archive contents...
Moving python_graph_core-1.8.2-py2.7.egg to /data1/bcbio/anaconda/lib/python2.7/site-packages
Adding python-graph-core 1.8.2 to easy-install.pth file

Installed /data1/bcbio/anaconda/lib/python2.7/site-packages/python_graph_core-1.8.2-py2.7.egg
Processing dependencies for python-graph-core==1.8.2
Finished processing dependencies for python-graph-core==1.8.2

but:

ls: cannot access /data1/bcbio/anaconda/lib/python2.7/site-packages/python_graph_core-1.8.2-py2.7.egg/pygraph/: Not a directory

Still error.

**Comment by chapmanb** [comment] 2015-03-12 09:57
Thanks for the additional information. It looks like the issue is the use of `easy_install` here, which installs this as a binary egg instead of a flag directory like pip. Your best bet it to uninstall this and re-install with pip:
```
/data1/bcbio/anaconda/bin/conda install pip
/data1/bcbio/anaconda/bin/pip uninstall python-graph-core
/data1/bcbio/anaconda/bin/pip install --allow-external python-graph-core --allow-unverified python-graph-core python-graph-core
```
Sorry for the issues. Python installation is tricky and doesn't always put things as expected. Hope this helps fix it.

**Comment by junchend** [comment] 2015-03-12 12:58
Thanks, Brad, I tried it, and 


Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x2ab2c8db24d0>
INFO: <cloudbio.flavor.Flavor instance at 0x2ab2c8db24d0>
INFO: This is a ngs_pipeline_minimal flavor
INFO: This is a ngs_pipeline_minimal flavor
INFO: Distribution __auto__
INFO: Distribution __auto__
INFO: Get local environment
INFO: Get local environment
INFO: CentOS setup
INFO: CentOS setup
DBG [distribution.py]: Checking target distribution centos
DBG [distribution.py]: Checking target distribution centos
DBG [distribution.py]: Unknown target distro
DBG [distribution.py]: Unknown target distro
WARN [distribution.py(211)]: NixPkgs are currently not supported for centos
WARN [distribution.py(211)]: NixPkgs are currently not supported for centos
DBG [distribution.py]: NixPkgs: Ignored
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'seq'],)
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'seq'],)
Traceback (most recent call last):
  File "bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/data1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/data1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 248, in upgrade_bcbio_data
    subprocess.check_call([gemini, "update", "--dataonly"] + extras)
  File "/data1/bcbio/anaconda/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/data1/bcbio/anaconda/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/data1/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/data1/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


It looks python-graph-core is ok, and other error occurred,

**Comment by chapmanb** [comment] 2015-03-12 13:21
Sorry about the continued issues. It looks like something happened with your installation -- there is no gemini executable in the directory even though the installation thinks it's there. It would help to know what command you're running but doing:
```
bcbio_nextgen.py upgrade --tools --toolplus data --data
```
Should first install gemini before trying to upgrade it and hopefully fix the issue.

**Comment by junchend** [comment] 2015-04-09 07:53
Hi Brad,

Error info when update bcbio:

Creating manifest of installed packages in /usr/local/share/bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 80, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 372, in _install_toolplus
    system_config = os.path.join(_get_data_dir(), "galaxy", "bcbio_system.yaml")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 444, in _install_gemini
    for line in r.text.split():
UnboundLocalError: local variable 'latest_version' referenced before assignment


It looks the update for main part of bcbio was fine, but the third parts tools failed, no more error message, could you please have a look at this?

Thanks !

**Comment by junchend** [comment] 2015-04-09 07:59
error message when re-run: bcbio_nextgen.py upgrade --tools --toolplus data --data


Third party tools upgrade complete.
Installing additional tools
/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 84, in upgrade_bcbio
    _install_toolplus(args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 376, in _install_toolplus
    _install_gemini(args.tooldir, _get_data_dir(), args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 448, in _install_gemini
    if LooseVersion(latest_version) > LooseVersion(cur_version):
UnboundLocalError: local variable 'latest_version' referenced before assignment

**Comment by chapmanb** [comment] 2015-04-09 08:50
Sorry about the issue. There was a release of GEMINI last night which changed the version specification in the requirements file slightly, and our code was not detecting it. I pushed a fix which will handle this so if you update:
```
bcbio_nextgen.py upgrade -u development
```
before running the tools/data upgrade it should now work cleanly. Thanks much for the report and hope this works for you now.

**Comment by roryk** [comment] 2015-10-05 21:15
Looks like this was fixed. Thanks for the report @junchend.

**Closed by roryk** 2015-10-05 21:15 UTC
