### ISSUE TITLE
Error running bcbio with ipython on torque system

### ISSUE THREAD

**Issue by MBeyens** [chapmanb/bcbio-nextgen#1595] opened 2016-10-11 10:16 UTC
Hi!

First of all, this pipeline is highly flexible and following the current best ngs practices. I developed my own pipelines, but I'm currently switching to this community maintained pipeline!

Running locally works perfect, but when I switches to our cluster environment (torque based) I ran in some errors. I have different nodes in the system, and every nodes has his folder to pick its binaries out. The problem is that the cluster jobs uses the wrong python (the real environment on that nodes) and not bcbios anaconda python. And so I get an ImportError, undefined symbol: PyUnicodeUCS2_AsASCIIString.

Below you find the running command and attached you find a part of the error. 

As you'll see in the attached file, its using `/opt/software/python2.7.5/lib/python2.7/site-packages/numpy/core/multiarray.so` and not the version of `/home/myname/local/share/bcbio/anaconda/`.

**Command:**
`/home/myname/local/share/bcbio/anaconda/bin/python /home/myname/local/bin/bcbio_nextgen.py ../config/XXX_SampleInfo-merged.yaml -t ipython -n 72 -s torque -q Development --tag dev -r account=myname`

[error_torque.txt](https://github.com/chapmanb/bcbio-nextgen/files/521541/error_torque.txt)

Thank you in advance!

**Comment by MBeyens** [comment] 2016-10-11 11:32
Suggestion, maybe implement your environment via qsub using the argument `qsub -V`? Like `-r environment=true` codes for #PBS -V

**Comment by schelhorn** [comment] 2016-10-11 12:27
Hmm, strange - we're running bcbio on torque as well, with no issues at all. The compute nodes have their own python as well, but the bcbio worker processes are correctly using the anaconde python. Perhaps sharing your `qstat -f` may help us to diagnose the issue?

**Comment by MBeyens** [comment] 2016-10-11 13:42
Hi, find in the attachment the output of `qstat -f`.

[error_log_server.txt](https://github.com/chapmanb/bcbio-nextgen/files/521926/error_log_server.txt)

**Comment by chapmanb** [comment] 2016-10-11 15:20
Thanks for using bcbio and apologies about the issue. We currently inherit the parent environment in the submission scripts as you suggest, so we'll have to dig a bit further: 

https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L690

It appears as if your compute nodes are adjusting LD_LIBRARY_PATH, maybe by module loading python or numpy, and this results in injecting incompatible shared libraries into the bcbio python environment. Is it possible to unset LD_LIBRARY_PATH or avoid this module load on the compute nodes to work around the problem? Hope this helps.

**Comment by lpantano** [comment] 2017-03-14 20:20
Hi @MBeyens 

I am closing this because it seems is not a problem anymore?, please feel free to open an issue if you find again the problem.

thanks!

**Closed by lpantano** 2017-03-14 20:20 UTC

**Comment by MBeyens** [comment] 2017-03-16 12:53
Hello

Thank you for asking!

At the moment I'm running it locally, but of course this is not really time efficient with large amount of samples to process. I still get the same error: `[0:apply]: ImportError: /opt/software/python2.7.5/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsASCIIString`. 
If it is importing its local variable of my screen session. So the pipeline is working fine locally but not when using parallel option... Apparently some where in the pipeline the script is importing the cluster variable paths and not my user (screen) paths to the lib.

Kind regards

Matthias

**Comment by chapmanb** [comment] 2017-03-16 14:13
Matthias;
The issue is that an alternative python installation, from `/opt/software/python2.7.5` gets injected into your python libraries and is incompatible with the bcbio installed python. Are you loading modules or otherwise including this module into your LD_LIBRARY_PATH? It might be worth asking your cluster admins if they know how this python gets included and we could suggest ways to remove it when running bcbio to avoid the incompatibility. Hope this helps.

**Comment by AlessandroGorohovski** [comment] 2017-07-31 14:16
Hi There,
Sorry, but I have a similar problem.
When I'm installing bcbio_nextgen:

$ python bcbio_nextgen_install.py ~/local/share/bcbio --tooldir=~/local --genomes GRCh37 --aligners bwa --aligners bowtie2 --distribution centos

or by using a command:
~/local/share/bcbio/anaconda/bin/python bcbio_nextgen_install.py ~/local/share/bcbio --tooldir=~/local --genomes GRCh37 --aligners bwa --aligners bowtie2 --distribution centos

I get an ImportError, undefined symbol: PyUnicodeUCS2_AsASCIIString.

my LD_LIBRARY_PATH is empty:
$ echo $LD_LIBRARY_PATH

 The CentOS system has python 2.6.6 as default.
2.6.6 (r266:84292, Aug 18 2016, 15:13:37)

but 
$  ~/local/share/bcbio/anaconda/bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

Sorry, how should I fix this problem?

Thank you in advance,
Alessandro

**Comment by chapmanb** [comment] 2017-07-31 17:56
Alessandro;
Thanks for the report and sorry about the issue. Could you provide a full traceback from the error you're seeing? You can post this as a gist (https://gist.github.com/). That should give us an idea where the problematic python libraries get injected into bcbio's load path, causing the issue. As a guess, do you have a dot local python directory (`~/.local`)? That often causes issues and removing it would avoid the problem there. Hope this helps.

**Comment by AlessandroGorohovski** [comment] 2017-08-01 07:11
Hello chapmanb,

Many thank for your asking,
Today I restarted the installation of bcbio-nextgen again as:

`$ python bcbio_nextgen_install.py ~/local/share/bcbio --tooldir=~/local --genomes GRCh37 --aligners bwa --aligners bowtie2 --distribution centos`

and received the same error message. Please see attached file:
[bcbio-nextgen_install.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/1189730/bcbio-nextgen_install.log.txt)

About a dot local python directory (`~/.local`).
I have no such directory.

Yeah, sure I looked http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

Regards, 
Alessandro,

**Comment by chapmanb** [comment] 2017-08-01 19:04
Alessandro;
Thanks for the detailed report. It looks like the problem is that there's another numpy install in your home directory, at `/home/alessandro/lib/python2.7/site-packages/numpy`. This is getting injected into your python import path somehow, causing the incompatibilities. If you don't need that, you can remove it and it should hopefully avoid the issue. If you do need it you'd need to dig into your `PYTHONPATH` or other environmental variables to determine how it gets included. Hope this helps with keeping things moving on your install.

**Comment by AlessandroGorohovski** [comment] 2017-08-02 06:39
Hello Brad,

Yes, I agree with you. You are right 100500% :)
Yesterday I thought about your assumption and
managed to install your wonderful bcbio-nextgen after magic:
$ unset PYTHONHOME
$ unset PYTHONPATH
$ export PYTHONNOUSERSITE=1

Thank you very much for your time and help!
Alessandro

Sorry, perhaps you could give an example or link of configuration yaml file for smallRNA-seq.
Of course ,I looked at the guide https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#smallrna-seq
but  I could not understand how to properly configure all the tools.

Thanks in advance,
Alessandro

**Comment by roryk** [comment] 2017-08-02 11:37
Hi Alessandro,

The options will depends a bit on your experiment-- https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#smallrna-sequencing has some information about the options you can set for smallRNA-seq and there is an example configuration file here: https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/templates/illumina-srnaseq.yaml

Hope that gets you started.

**Comment by AlessandroGorohovski** [comment] 2017-08-02 12:34
Hi Rory,

Your advice is like fresh air during this heat.
Thank you very much for enlightenment of my brain  :)

Have a nice day,
Alessandro

**Comment by pdarakjiank** [comment] 2017-09-20 23:00
Brilliant. Have been facing this issue over and over. Got it resolved thanks to this discussion.
