### ISSUE TITLE
GATK Memory errors using bcbio-vm

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1654] opened 2016-11-25 15:46 UTC
Hello,

I'm getting a memory error while running bcbio (using bcbio-vm) when running on an Azure instance (specifically, Standard_A10 with 8 cpu and 56gb memory).
Below is what I have in bcbio_system-merged.yaml file.

I can't understand why it fails. I tried before giving less memory per core (2-3gb) and it failed on an earlier stage (BaseRecalibrator). 
I'm setting the cores and memory using "bcbio_vm.py devel system 8 3000".

What is the needed memory per  core? What are the other factors affecting the resources allocation?

Thank you for your help,
Y.

**last commands from the log**
[2016-11-25T14:58Z] java -Xms454m -Xmx5727m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/work/tx/tmpFYVR0_ -jar /mnt/work/inputs/jars/gatk/GenomeAnalysisTK.jar -T PrintReads -L chr9:1-141213431 -R /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa -I /mnt/work/align/test_sample/test_sample-sort.bam -BQSR /mnt/work/align/test_sample/test_sample-sort.grp -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /mnt/work/bamprep/test_sample/chr9/tx/tmpTmFnyz/test_sample-sort-chr9_0_141213431-prep.bam
[2016-11-25T14:58Z] java -Xms454m -Xmx5727m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/work/tx/tmpRRbqeB -jar /mnt/work/inputs/jars/gatk/GenomeAnalysisTK.jar -T PrintReads -L chr10:1-135534747 -R /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa -I /mnt/work/align/test_sample/test_sample-sort.bam -BQSR /mnt/work/align/test_sample/test_sample-sort.grp -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /mnt/work/bamprep/test_sample/chr10/tx/tmpLYRrPn/test_sample-sort-chr10_0_135534747-prep.bam

**bcbio_system-merged.yaml**
galaxy_config: universe_wsgi.ini
resources:
  default:
    cores: 8
    jvm_opts:
    - -Xms750m
    - -Xmx6300m
    memory: 6300M
  dexseq:
    memory: 10g
  express:
    memory: 8g
  gatk:
    jvm_opts:
    - -Xms500m
    - -Xmx6300m
  macs2:
    memory: 8g
  qualimap:
    memory: 6300m
  seqcluster:
    memory: 8g
  snpeff:
    jvm_opts:
    - -Xms750m
    - -Xmx6300m

**GATK error**
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
___________________________________________________________________________
' returned non-zero exit status 1

**Comment by chapmanb** [comment] 2016-11-26 02:39
Thanks for the detailed report and sorry about the issue. GATK is telling you it need more memory per process so you'd need to increase the `gatk: jvm_opts` memory in `-Xmx` to something larger than `6300m`. This should have been enough memory based on past experience but it's hard to give a recommendation because this is dependent on read depth and I don't have a good feel for why memory requirements something explode on some samples.

Beyond increasing memory, do you need recalibration and realignment in your analysis? We typically skip these (set `recalibrate: false` `realign: false`, or just remove them in any recent versions since this is the default) and avoid the extra computational and disk IO overhead of running them.

Hope either option gets your analysis completed.

**Comment by deber1980** [comment] 2017-01-25 14:49
Hello Brad,

I'm following up on this issue as I'm still encountering issues with GATK memory, now during using HaplotypeCaller. The following command 
`
java   -Xms681m -Xmx6000m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/work/tx/tmpYCM_Mg -jar /mnt/work/inputs/jars/gatk/GenomeAnalysisTK.jar 
-R /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation GCContent --annotation HaplotypeScore 
--annotation HomopolymerRun --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest 
--annotation RMSMappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /mnt/work/align/sample123/sample123-sort.bam 
--dbsnp /mnt/work/inputs/data/genomes/hg19/variation/dbsnp_138.vcf.gz -L /mnt/work/gatk-haplotype/chr1/sample123_batch-chr1_0_249250621-regions.bed 
--interval_set_rule INTERSECTION -drf DuplicateRead -T HaplotypeCaller -o /mnt/work/gatk-haplotype/chr1/tx/tmp43NdK5/sample123_batch-chr1_0_249250621.vcf.gz 
--annotation ClippingRankSumTest --annotation DepthPerSampleHC --pair_hmm_implementation VECTOR_LOGLESS_CACHING -ploidy 2 -U LENIENT_VCF_PROCESSING 
--read_filter BadCigar --read_filter NotPrimaryAlignment > gatkrun.-java8log &
`


Fails with this memory error:
>  ##### ERROR MESSAGE: An error occurred because you did not provide enough memory to run this program. You can use the -Xmx argument (before the -jar argument) to adjust the maximum heap size provided to Java. Note that this is a JVM argument, not a GATK argument.

Increasing the -Xmx6000m to something like 20GB fixed it, but that a lot of memory just for a single thread.
After some investigation it seems that the thing that would help the most is reducing the called region. For me it worked when reducing by half  i.e. from putting chr1:0-249250621 in the bed, change to chr1:0-150000000.
I wanted to ask how does bcbio determine how to divide the regions for the calling? Is there a way to control it further? Any other tips that can help with resolving this?

Thank you in advance,
Y.

**Comment by chapmanb** [comment] 2017-01-25 17:14
The whole chromosome contigs were a bug in a previous bcbio version that should be fixed now. If you update to the latest Docker image (or latest external bcbio if you're using that instead of bcbio-vm) it should now create chromosome sections instead of whole chromosomes. Practically I don't think this is the cause of the memory usage, which is more often due to depth and complexity at positions rather than length of the chromosome. However, it might help with removal of high depth or other problem regions in the latest release.

If you're still having memory issues it might help to isolate to a specific region where memory gets out of control, which you could do from the GATK logs as it walks across the file. This might end up being a question fo the Broad team but having a smaller reproducible case with high memory could help define the underlying issue. Hope this helps.

**Comment by deber1980** [comment] 2017-01-25 20:36
Thanks Brad. Very helpful. I'll update the code and see if it reproduces or not.

**Closed** 2017-01-29 07:52 UTC
