### ISSUE TITLE
"germline" present in multiple tumor samples causes multiple QC runs of the normal (?)

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2154] opened 2017-11-13 09:14 UTC
Note the (?) in the title, because I'm not sure what is the actual cause. I noticed that one of my normal samples was run repeatedly over QC (as up as 5-6 times): this included downsampling, mapped reads with samtools and FastQC runs (at a point some failed because the file they were using got overwritten).

The YAML template specified `germline` variant calling for all samples, out of simplicity because I know that the setting is ignored in tumor samples. That's my (current) only clue, but I can't test easily the same configuration without it (very deep reads, long time processing).

**Comment by lbeltrame** [comment] 2017-11-13 10:04
I've noticed this also with other samples: QC failed because two nodes ran the same QC (`idxstats`), one finishing earlier than the other and thus causing an exception for `shutil` (because the file already existed).

**Comment by chapmanb** [comment] 2017-11-13 11:06
Luca -- thanks for the report. I'm cc'ing in @vladsaveliev since he worked on germline QC most recently and would have the best understanding of potential issues. Can you describe your sample YAML so we can try to reproduce? Is this a normal shared amongst multiple tumors? Ideally we'd try to replicate the behavior on a small test to help us diagnose. Any error messages or tracebacks you saved from the race condition would also be helpful to pinpoint issues. Thanks much.

**Comment by vladsaveliev** [comment] 2017-11-14 07:55
Thanks for the report!

I created a PR that will hopefully fix it. The issue was that during one of the stages, bcbio was adding a copy of normal into the processing list for each batch the normal belongs. So I fixed it to regroup samples back as before this stage, keeping only one normal sample.

Vlad

**Comment by chapmanb** [comment] 2017-11-14 10:47
Luca -- this should be fixed in latest development with #2157. Please let us know if you run into any other issues and thank you again for letting us know about the issue.

**Closed by chapmanb** 2017-11-14 10:47 UTC
