### ISSUE TITLE
Conda bug breaks fresh install

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1683] opened 2016-12-12 12:55 UTC
Hi Brad, 

I was trying to get a "clean" install of bcbio and got the following error:

```
   ....
    yamllint:                           1.5.0-py27_0
    zeromq:                             4.1.5-0

The following packages will be UPDATED:

    conda:                              4.0.5-py27_0 --> 4.2.13-py27_0
    conda-env:                          2.4.5-py27_0 --> 2.6.0-0
    python:                             2.7.11-0     --> 2.7.12-1
    sqlite:                             3.9.2-0      --> 3.13.0-0

Error: Missing write permissions in: /opt/bcbio/anaconda
....
```

I believe this is due to a bug in the conda installer. By changing the miniconda installer version
```
REMOTES = {
    "requirements": "https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt",
    "gitrepo": "git://github.com/chapmanb/bcbio-nextgen.git",
    "system_config": "https://raw.github.com/chapmanb/bcbio-nextgen/master/config/bcbio_system.yaml",
    "anaconda": "https://repo.continuum.io/miniconda/Miniconda-latest-%s-x86_64.sh"}
``` 

to

```
REMOTES = {
    "requirements": "https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt",
    "gitrepo": "git://github.com/chapmanb/bcbio-nextgen.git",
    "system_config": "https://raw.github.com/chapmanb/bcbio-nextgen/master/config/bcbio_system.yaml",
    "anaconda": "https://repo.continuum.io/miniconda/Miniconda2-4.2.12-%s-x86_64.sh"}
```

I was able to resolve the issue. Conda itself gets updated during the installation process, so no real harm done.

Just wanted to give you a heads-up.
M

**Comment by chapmanb** [comment] 2016-12-13 02:04
Matthias;
Thanks for the report. I've been trying to reproduce this issue and am not able to so am trying to better understand the error. It looks like you were trying to install to `/opt/bcbio` and had a permissions issue, is that right? Is it possible the permission problem was resolved prior to retrying? It looks from the checksums like `latest` and `4.2.12` are the same:

https://repo.continuum.io/miniconda/

so I'm not sure why one would work and the other not. Thanks for any additional details.

**Comment by matthdsm** [comment] 2016-12-13 07:02
Hey Brad,

I think this is going to be some freak occurence, I'm 100% sure the target directory is writable by my user (I made the dir). I really have no idea why this would happen, but I've had the same issue in other directories, even my home folder, prior to submitting the issue. Does the installer script modify permissions somewhere? I was able to install miniconda in the same directory, using the `latest` installer, and I was able to create a new env and install stuff. Come to think of it, I actually got the issue most of the time when I was trying to install bcbio-nextgen from bioconda. Could there be a dependency or something causing this?

Either way, it's fixed for now, and most probably had something to do with our setup here.

M

**Comment by chapmanb** [comment] 2016-12-13 14:56
Matthias;
Thanks for the additional details. If things are working I'll close this for now and we can reinvestigate later if needed. If we need to revisit it would be helpful to see the full error command, it looks like conda might provide other helpful debugging output to figure out what is going on:

https://github.com/conda/conda/blob/8257927e0061f537f77a6999e971a33331dec941/conda/cli/help.py

Thanks again.

**Closed by chapmanb** 2016-12-13 14:56 UTC
