### ISSUE TITLE
STAR produce empty bam files

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2203] opened 2017-12-29 14:17 UTC
Hi, I am using bcbio to process my RNA-seq samples. I used the STAR aligner to do alignment. My template is as below
> upload:
>   dir: upload
> details:
>   \- analysis: RNA-seq
>     algorithm:
>       aligner: star
>       quality_format: standard
>       expression_caller: [stringtie, dexseq, kallisto, salmon]
>     metadata:
>       batch: TestBatch1
>     description: Test1
>     genome_build: hg19
> 

The STAR log looks good, but the output bam file is only 104K and its final.log is strange:

>                                  Started job on |       Dec 29 14:51:19
>                              Started mapping on |       Dec 29 15:17:49
>                                     Finished on |       Dec 29 15:18:02
>        Mapping speed, Million of reads per hour |       0.00
> 
>                           Number of input reads |       0
>                       Average input read length |       0
>                                     UNIQUE READS:
>                    Uniquely mapped reads number |       0
>                         Uniquely mapped reads % |       0.00%
>                           Average mapped length |       0.00
>                        Number of splices: Total |       0
>             Number of splices: Annotated (sjdb) |       0
>                        Number of splices: GT/AG |       0
>                        Number of splices: GC/AG |       0
>                        Number of splices: AT/AC |       0
>                Number of splices: Non-canonical |       0
>                       Mismatch rate per base, % |       -nan%
>                          Deletion rate per base |       0.00%
>                         Deletion average length |       0.00
>                         Insertion rate per base |       0.00%
>                        Insertion average length |       0.00
>                              MULTI-MAPPING READS:
>         Number of reads mapped to multiple loci |       0
>              % of reads mapped to multiple loci |       0.00%
>         Number of reads mapped to too many loci |       0
>              % of reads mapped to too many loci |       0.00%
>                                   UNMAPPED READS:
>        % of reads unmapped: too many mismatches |       0.00%
>                  % of reads unmapped: too short |       0.00%
>                      % of reads unmapped: other |       0.00%
>                                   CHIMERIC READS:
>                        Number of chimeric reads |       0
>                             % of chimeric reads |       0.00%
> 

Furthermore, I found the STAR alignment command in its log file and it is as below:
`/app/smartngs/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /app/smartngs/bcbio/genomes/Hsapiens/hg19/star/ --readFilesIn /app/datamart/RNAseq-example/seqc-test/input/SRR950083_1.fastq.gz /app/datamart/RNAseq-example/seqc-test/input/SRR950083_2.fastq.gz --runThreadN 16 --outFileNamePrefix /app/datamart/RNAseq-example/seqc_star/work/bcbiotx/tmpuScyot/HBRR_rep3/HBRR_rep3 --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted --limitOutSJcollapsed 2000000 --outSAMtype BAM Unsorted --outSAMunmapped Within --outSAMattributes NH HI NM MD AS --sjdbGTFfile /app/smartngs/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf --sjdbOverhang 100 --readFilesCommand zcat --outSAMattrRGline ID:HBRR_rep3 PL:illumina PU:HBRR_rep3 SM:HBRR_rep3 --outSAMstrandField intronMotif --quantMode TranscriptomeSAM`

I run this command directly and found it did produce almost empty bam file. How to work out this problem?

**Comment by chapmanb** [comment] 2017-12-30 03:10
Thanks for the report and sorry about the issue. Is it possible there is something problematic about your STAR index in `/app/smartngs/bcbio/genomes/Hsapiens/hg19/star`? I tried downloading those files from the ENA and mapping the first couple thousand of them and then worked cleanly. You might want to try rebuilding the STAR index file if something went wrong on the initial run. Hope this helps explain the issue.

**Comment by hliu2016** [comment] 2017-12-30 04:46
@chapmanb 
Thanks for your help. I have rebuild the index with the command:
`STAR --runMode genomeGenerate --runThreadN 16 --genomeFastaFiles /app/smartngs/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa --sjdbGTFfile /app/smartngs/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf --sjdbOverhang 100 --genomeDir /app/smartngs/bcbio/genomes/Hsapiens/hg19/star`
and the index was successfully built. The index files looks allright:

> -rw-r--r--. 1 root root         688 Dec 30 11:19 chrLength.txt
> -rw-r--r--. 1 root root        1971 Dec 30 11:19 chrNameLength.txt
> -rw-r--r--. 1 root root        1283 Dec 30 11:19 chrName.txt
> -rw-r--r--. 1 root root        1017 Dec 30 11:19 chrStart.txt
> -rw-r--r--. 1 root root    42355628 Dec 30 11:56 exonGeTrInfo.tab
> -rw-r--r--. 1 root root    17170655 Dec 30 11:56 exonInfo.tab
> -rw-r--r--. 1 root root      917974 Dec 30 11:56 geneInfo.tab
> -rw-r--r--. 1 root root  3220649459 Dec 30 12:00 Genome
> -rw-r--r--. 1 root root         714 Dec 30 11:16 genomeParameters.txt
> -rw-r--r--. 1 root root       30352 Dec 30 12:07 Log.out
> -rw-r--r--. 1 root root 24468343172 Dec 30 12:07 SA
> -rw-r--r--. 1 root root  1565873619 Dec 30 12:07 SAindex
> -rw-r--r--. 1 root root    10045271 Dec 30 11:56 sjdbInfo.txt
> -rw-r--r--. 1 root root     8874600 Dec 30 11:56 sjdbList.fromGTF.out.tab
> -rw-r--r--. 1 root root     8872733 Dec 30 11:56 sjdbList.out.tab
> -rw-r--r--. 1 root root    11596959 Dec 30 11:56 transcriptInfo.tab
> 

Then, I run the STAR to do alignment using the command generated by bcbio as below:
`/app/smartngs/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /app/smartngs/bcbio/genomes/Hsapiens/hg19/star/ --readFilesIn /app/datamart/RNAseq-example/seqc-test/input/SRR950083_1.fastq.gz /app/datamart/RNAseq-example/seqc-test/input/SRR950083_2.fastq.gz --runThreadN 16 --outFileNamePrefix /app/datamart/RNAseq-example/seqc_star/work/bcbiotx/tmpuScyot/HBRR_rep3/HBRR_rep3 --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted --limitOutSJcollapsed 2000000 --outSAMtype BAM Unsorted --outSAMunmapped Within --outSAMattributes NH HI NM MD AS --sjdbGTFfile /app/smartngs/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf --sjdbOverhang 100 --readFilesCommand zcat --outSAMattrRGline ID:HBRR_rep3 PL:illumina PU:HBRR_rep3 SM:HBRR_rep3 --outSAMstrandField intronMotif --quantMode TranscriptomeSAM`
However, the output bam files is still small and I can see nothing by samtools view command. I am really puzzled by this problem.

**Comment by chapmanb** [comment] 2017-12-30 20:42
Thanks for following up and sorry that rebuilding the index didn't resolve the issue. I tried to reproduce with your exact command line and first few thousand fastq inputs from this ENA repository, which I guessed is the source of your fastqs from your command line:

https://www.ebi.ac.uk/ena/data/view/SRR950083

and it runs without any issues producing mapping reads.

At this point my suggestion would be try and produce a minimal example that can reproduce the issue. How did you retrieve and prepare these fastq inputs? Is it possible something was problematic there? If you cannot identify anything and could share a small set of inputs we could look at those to see if anything looks off.

Another idea to debug is to try a different aligner like hisat2 to determine if there is something wrong with the reads themselves or running STAR. If the former, hisat2 will also have issues. If the later, then you expect hisat2 to work correctly.

Thank you for the help debugging.

**Comment by hliu2016** [comment] 2017-12-31 00:38
@chapmanb 
I am very grateful for your help. Yes, I have tested hisat2 aligner and it run successfully. So, I think this problem is caused by STAR itself. However, I can not find the solution. Thanks again.

**Comment by chapmanb** [comment] 2017-12-31 01:16
Thanks for debugging and helping isolate the issues. Looking through your logs the only thing I can notice is that you're using an older version of STAR (2.5.2b) while bcbio ships with 2.5.3a. Is it possible to upgrade (`bcbio_conda install -c conda-forge -c bioconda star`) to see if that fixes the issue?

Beyond that, the next step is to try and create a minimal example of two small fastqs that demonstrate the problem and share those. You should be able to do with something like `zcat /app/datamart/RNAseq-example/seqc-test/input/SRR950083_1.fastq.gz | head -8000 | bgzip -c > SRR950083_1-min.fastq.gz` for each of the paired ends and then could test if that works and share if not.

Thanks again and hope this helps.

**Comment by hliu2016** [comment] 2017-12-31 08:33
@chapmanb 
Hi Dr. Chapman, I am really sorry to disturb you again. I now use hisat2 to do alignment for rn6 samples.
But unfortunately the pipeline failed in the quality control stage. The error information is

> Failed to run rnaseq
> java.lang.RuntimeException: BAM file is empty or no read alignments are located in exonic regions.
>         at org.bioinfo.ngs.qc.qualimap.process.ComputeCountsTask.run(ComputeCountsTask.java:559)
>         at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.run(RNASeqQCAnalysis.java:68)
>         at org.bioinfo.ngs.qc.qualimap.main.RnaSeqQcTool.execute(RnaSeqQcTool.java:188)
>         at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:190)
>         at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:111)
```

> 
> ' returned non-zero exit status 255
> return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
>     return apply(f, *args, **kwargs)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 191, in pipeline_summary
>     return qcsummary.pipeline_summary(*args)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 68, in pipeline_summary
>     data["summary"] = _run_qc_tools(work_bam, work_data)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 146, in _run_qc_tools
>     out = qc_fn(bam_file, data, cur_qc_dir)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 323, in run_rnaseq
>     do.run(cmd, "Qualimap for {}".format(dd.get_sample_name(data)))
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> subprocess.CalledProcessError: Command 'set -o pipefail; unset DISPLAY && export PATH=/app/smartngs/bcbio/anaconda/bin:$PATH &&  /app/smartngs/bcbio/galaxy/../anaconda/
> bin/qualimap rnaseq -outdir /app/datamart/jieyi_bio/rat_hisat2/work/bcbiotx/tmp4K4cuX/3_21D_rep1 -a proportional -bam /app/datamart/jieyi_bio/rat_hisat2/work/align/3_21
> D_rep1/3_21D_rep1.bam -p non-strand-specific -gtf /app/smartngs/bcbio/genomes/Rnorvegicus/rn6/rnaseq/ref-transcripts.gtf --java-mem-size=59g
> 

```

**Comment by chapmanb** [comment] 2017-12-31 11:21
Thanks for following up, this looks like a similar error to what you saw with the other run but expressed differently. It appears as if there are no reads aligned in any transcript regions so it's failing basic sanity checks when run through qualimap QC.

To diagnose this or the other error we'd need more information about how the fastqs were prepared and minimal examples that demonstrate the problem. It appears as if there is something problematic about these inputs but it's hard to guess what with only the error message. Hope this helps.

**Comment by hliu2016** [comment] 2017-12-31 13:16
@chapmanb 
Thanks for your help. I have created a minimal example from my fastq files. I hope you can make a test for my data. Thanks a lot.

[3_21D1_R2.fastq.gz](https://github.com/chapmanb/bcbio-nextgen/files/1595183/3_21D1_R2.fastq.gz)
[3_21D1_R1.fastq.gz](https://github.com/chapmanb/bcbio-nextgen/files/1595184/3_21D1_R1.fastq.gz)

**Comment by hliu2016** [comment] 2017-12-31 13:44
@chapmanb 
Thanks for your kind help. I think I have found the reason caused this strange problem. I am using the Glusterfs  distributed file system to store the fastq files. Just now I move the fastq files to a local disk, and then STAR run successfully!  So, I guess this is caused by the STAR parameter --readFilesCommand zcat,  which failed to read the fastq files stored in Glusterfs file system. 

Do you know something to tackle this?

**Comment by chapmanb** [comment] 2018-01-02 11:12
Thanks for following up with this. I pushed a fix that will hopefully resolve this by changing from using `--readFilesCommand` to using the process substitution trick from Alex. If you update to the latest development (`bcbio_nextgen.py upgrade -u development`) and re-run I hope it will work cleanly for you. Thanks again for the help debugging and hope this gets your analysis working.

**Closed** 2018-01-02 11:11 UTC
