### ISSUE TITLE
bcbio-sv cn.mops error on example data

### ISSUE THREAD

**Issue by pallolason** [chapmanb/bcbio-nextgen#604] opened 2014-09-23 05:52 UTC
Hi,

When running the bcbio structural variation example I get this cn.mops error when processing chr Y:

    Normalizing...
    Error in if (n > 512) n <- 2^ceiling(log2(n)) : 
    missing value where TRUE/FALSE needed
    Calls: cn.mops ... normalizeChromosomes -> density -> density -> density.default
    In addition: Warning message:
    In normalizeChromosomes(X, chr = chr, normType = normType, qu = normQu) :
    Some normalization factors are zero!
    Execution halted
    ' returned non-zero exit status 1
  
Any ideas? 

Cheers,
Pall

**Comment by druvus** [comment] 2015-01-12 17:41
Brad, 
I managed to reproduce the same error as Pall for the SV example data using latest bcbio devel version (R version 3.1.2) and cn.mops_1.12.0 so I tried to find the reason behind the error. 

The errors seems to happen in the normalizeChromosomes function when cn.mops analyses data from  Y chromosomes of female samples (i.e. NA12878 and NA12892) which leads to too low coverage. Also tried devel version of cn.mops_1.13.1  and it suggests: 

> "Remove samples or chromosomes for which the average read count is zero,", "e.g. chromosome Y." 

A possible solution to fix this issue could be to skip cn.mops analysis on chromosome Y for female samples.

/Andreas

**Comment by chapmanb** [comment] 2015-01-14 15:20
Andreas;
Thanks so much for the detective work. I pushed a fix which will catch this issue and continue writing no calls on that chromosome. That should hopefully let these continue cleanly and give good calls everywhere else. Thanks again for all the help debugging this.

**Closed** 2015-01-14 15:19 UTC
