### ISSUE TITLE
multiqc issue

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1584] opened 2016-09-30 13:34 UTC
Hi,

We're having a problem with multiqc when using hg38 (with hg19 it seems to work).

Any ideas?

Here is an output from bcbio-nextgen:

```
`[2016-09-30T13:21Z] Run multiqc
[2016-09-30T13:21Z] [INFO   ]         multiqc : This is MultiQC v0.8.dev0
[2016-09-30T13:21Z] [INFO   ]         multiqc : Template    : default
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/44M/fastqc'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/49H/fastqc'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/13L/fastqc'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/8M/fastqc'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/47H/fastqc'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/multiqc/report/metrics'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching '/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/41L/fastqc'
[2016-09-30T13:21Z] [INFO   ]         multiqc : Searching 'trimmed'
[2016-09-30T13:21Z] [ERROR  ]         multiqc : Oops! The 'bcbio' MultiQC module broke...
[2016-09-30T13:21Z]                     Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
[2016-09-30T13:21Z]                     (if possible, include a log file that triggers the error)
[2016-09-30T13:21Z] ============================================================
[2016-09-30T13:21Z] Module bcbio raised an exception: Traceback (most recent call last):
[2016-09-30T13:21Z]   File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/multiqc-0.8.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 304, in multiqc
[2016-09-30T13:21Z]     report.modules_output.append(mod())
[2016-09-30T13:21Z]   File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/multiqc_bcbio-0.1.4-py2.7.egg/multiqc_bcbio/bcbio.py", line 74, in __init__
[2016-09-30T13:21Z]     self.metrics_stats_table()
[2016-09-30T13:21Z]   File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/multiqc_bcbio-0.1.4-py2.7.egg/multiqc_bcbio/bcbio.py", line 208, in metrics_stats_table
[2016-09-30T13:21Z]     self.general_stats_addcols(self.bcbio_data, headers)
[2016-09-30T13:21Z]   File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/multiqc-0.8.dev0-py2.7.egg/multiqc/modules/base_module.py", line 153, in general_stats_addcols
[2016-09-30T13:21Z]     headers[k]['namespace'] = namespace
[2016-09-30T13:21Z] KeyError: '49H'
[2016-09-30T13:21Z] ============================================================
[2016-09-30T13:21Z] [INFO   ]          fastqc : Found 6 reports
[2016-09-30T13:21Z] [INFO   ]         multiqc : Report      : tx/tmpKpmc9T/multiqc_report.html
[2016-09-30T13:21Z] [INFO   ]         multiqc : Data        : tx/tmpKpmc9T/multiqc_data
[2016-09-30T13:21Z] [INFO   ]         multiqc : MultiQC complete
[2016-09-30T13:21Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail;  /home/bcbio_root/share/bcbio/galaxy/../anaconda/bin/multiqc -f /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/44M/fastqc /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/49H/fastqc /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/13L/fastqc /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/8M/fastqc /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/47H/fastqc /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/multiqc/report/metrics /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/qc/41L/fastqc trimmed  -o /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/calling/work/tx/tmpKpmc9T 
```

Here is the yaml file, if important:

```
`---
upload:
  dir: ../final
details:
  - files: [/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/13L_R1_val_1.fq, /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/13L_R2_val_2.fq]
    description: 13L
    metadata:
      batch: batch1
    analysis: smallRNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      species: hsa
      strandedness: unstranded
      quality_format: Standard
      trim_reads: read_through
      expression_caller: mirdeep2
  - files: [/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/41L_R1_val_1.fq, /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/41L_R2_val_2.fq]
    description: 41L
    metadata:
      batch: batch1
    analysis: smallRNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      species: hsa
      strandedness: unstranded
      quality_format: Standard
      trim_reads: read_through
      expression_caller: mirdeep2
  - files: [/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/44M_R1_val_1.fq, /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/44M_R2_val_2.fq]
    description: 44M
    metadata:
      batch: batch1
    analysis: smallRNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      species: hsa
      strandedness: unstranded
      quality_format: Standard
      trim_reads: read_through
      expression_caller: mirdeep2
  - files: [/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/47H_R1_val_1.fq, /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/47H_R2_val_2.fq]
    description: 47H
    metadata:
      batch: batch1
    analysis: smallRNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      species: hsa
      strandedness: unstranded
      quality_format: Standard
      trim_reads: read_through
      expression_caller: mirdeep2
  - files: [/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/49H_R1_val_1.fq, /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/49H_R2_val_2.fq]
    description: 49H
    metadata:
      batch: batch1
    analysis: smallRNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      species: hsa
      strandedness: unstranded
      quality_format: Standard
      trim_reads: read_through
      expression_caller: mirdeep2
  - files: [/home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/8M_R1_val_1.fq, /home/lindak/Data/LiquidBiopsies/mirna/160926/Trimmed10/8M_R2_val_2.fq]
    description: 8M
    metadata:
      batch: batch1
    analysis: smallRNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      species: hsa
      strandedness: unstranded
      quality_format: Standard
      trim_reads: read_through
      expression_caller: mirdeep2
```

**Comment by lpantano** [comment] 2016-09-30 16:18
Hi,

sorry about the issue. Can you send me the *debug.log file to see if I catch but qc file is missing for that sample. I guess that is the problem.

Thanks

**Comment by lindakohn** [comment] 2016-10-03 07:15
Hi,

I'm Linda and I'm working together with parlar on this. Attaching the debug log...

[bcbio-nextgen-debug.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/505673/bcbio-nextgen-debug.log.txt)

**Comment by lpantano** [comment] 2016-10-03 14:38
Hi,

The problem is the genome version, I didn’t port to hg38 yet, since I am not sure how the genome alignment will work.

What is the main goal of this analysis? like, do you want to annotate miRNAs only? or do something else?

The miRNA version will be the same for now for hg38 and hg19, since this depends on miRBase updates. What it would change is the alignment and all tools related to that, at this point, the rest for mirdeep2 and seqcluster. There is not a lot about how alignments for small RNA changed for this new version, so I a little nervous to move forward without doing some checking.

thanks

**Comment by lindakohn** [comment] 2016-10-04 13:43
OK, that's fine I can live with hg19 :-) Our aim is to annotate and quantify. I do however get issues with hg19 as well after alignment. Below is bcbio output...


Traceback (most recent call last):
  File "/home/bcbio_root/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bcbio_root/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 323, in smallrnaseqpipeline
    samples = run_parallel("srna_annotation", samples)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 84, in srna_annotation
    return srna.sample_annotation(*args)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 73, in sample_annotation
    data['seqbuster'] = _miraligner(data["collapse"], out_file, dd.get_species(data), mirbase, data['config'])
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 136, in _miraligner
    export = _get_env()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 153, in _get_env
    version = yaml.load(stdout.read())[0].split("-")[1]
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/scanner.py", line 159, in fetch_more_tokens
    self.stale_possible_simple_keys()
  File "/home/bcbio_root/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<string>", line 2, column 1:
    [
    ^
could not found expected ':'
  in "<string>", line 3, column 3:
      "bioconda::seqbuster-3.1-1"
      ^




And debug.log..

[2016-09-21T06:21Z] System YAML configuration: /home/bcbio_root/share/bcbio/galaxy/bcbio_system.yaml
[2016-09-21T06:21Z] Resource requests: cutadapt, picard; memory: 3.00, 3.00; cores: 16, 16
[2016-09-21T06:21Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2016-09-21T06:21Z] Timing: organize samples
[2016-09-21T06:21Z] multiprocessing: organize_samples
[2016-09-21T06:21Z] Using input YAML configuration: /home/lindak/Data/LiquidBiopsies/mirna/hg19test/calling/config/calling.yaml
[2016-09-21T06:21Z] Checking sample YAML configuration: /home/lindak/Data/LiquidBiopsies/mirna/hg19test/calling/config/calling.yaml
[2016-09-21T06:21Z] Testing minimum versions of installed programs
[2016-09-21T06:21Z] multiprocessing: prepare_sample
[2016-09-21T06:21Z] Preparing 1L
[2016-09-21T06:21Z] Timing: adapter trimming
[2016-09-21T06:21Z] multiprocessing: trim_srna_sample
[2016-09-21T06:21Z] Skip trimming for: 1L
[2016-09-21T06:54Z] Resource requests: picard, samtools, star; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2016-09-21T06:54Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2016-09-21T06:54Z] Timing: prepare
[2016-09-21T06:54Z] multiprocessing: seqcluster_prepare
[2016-09-21T06:54Z] You didn't specify any other expression caller tool.You can add to the YAML file:expression_caller:[trna, seqcluster, mirdeep2]
[2016-09-21T06:56Z] Timing: alignment
[2016-09-21T06:56Z] multiprocessing: srna_alignment
[2016-09-21T06:56Z] Aligning lane 1L with star aligner
[2016-09-21T06:56Z] Running STAR aligner on /home/lindak/Data/LiquidBiopsies/mirna/hg19test/calling/work/seqcluster/prepare/seqs.fastq and /home/bcbio_root/share/bcbio/genomes/Hsapiens/hg19/star/
[2016-09-21T06:57Z] Index BAM file: 1L.bam
[2016-09-21T06:57Z] Resource requests: miraligner, picard; memory: 3.00, 3.00; cores: 16, 16
[2016-09-21T06:57Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2016-09-21T06:57Z] Timing: small RNA annotation
[2016-09-21T06:57Z] multiprocessing: srna_annotation

**Comment by lpantano** [comment] 2016-10-04 13:47
Hi,

I addressed this issue a while ago, any chance you can update tools and bcbio and try again?

thanks!

**Comment by lindakohn** [comment] 2016-10-04 14:09
Will try that, thanks!

**Comment by lindakohn** [comment] 2016-10-06 13:39
It's working fine now, thank you! 

By the way, how are the count tables generated? Anything similar to HTSeq?

**Comment by lpantano** [comment] 2016-10-06 15:12
Good is working again.

Do you mean for miRNAs?

You can find more information here:  http://seqcluster.readthedocs.io/mirna_annotation.html <http://seqcluster.readthedocs.io/mirna_annotation.html>

**Comment by lpantano** [comment] 2016-11-03 22:58
Hi,

I will close this. Feel free to open other issue for any other question/problem.

thanks!

**Closed by lpantano** 2016-11-03 22:58 UTC
